# Devicons (198 icons, 7 do not have an established name)
# Codepoints: Nerd moved E600-E6C5 → E700-E7C5
set i ''; set -gx i_dev_bing_small $i
set i ''; set -gx i_dev_css_tricks $i
set i ''; set -gx i_dev_git $i
set i ''; set -gx i_dev_bitbucket $i
set i ''; set -gx i_dev_mysql $i
set i ''; set -gx i_dev_streamline $i
set i ''; set -gx i_dev_database $i
set i ''; set -gx i_dev_dropbox $i
set i ''; set -gx i_dev_github_alt $i
set i ''; set -gx i_dev_github_badge $i
set i ''; set -gx i_dev_github $i
set i ''; set -gx i_dev_wordpress $i
set i ''; set -gx i_dev_visualstudio $i
set i ''; set -gx i_dev_jekyll_small $i
set i ''; set -gx i_dev_android $i
set i ''; set -gx i_dev_windows $i
set i ''; set -gx i_dev_stackoverflow $i
set i ''; set -gx i_dev_apple $i
set i ''; set -gx i_dev_linux $i
set i ''; set -gx i_dev_appstore $i
set i ''; set -gx i_dev_ghost_small $i
set i ''; set -gx i_dev_yahoo $i
set i ''; set -gx i_dev_codepen $i
set i ''; set -gx i_dev_github_full $i
set i ''; set -gx i_dev_nodejs_small $i
set i ''; set -gx i_dev_nodejs $i
set i ''; set -gx i_dev_hackernews $i
set i ''; set -gx i_dev_ember $i
set i ''; set -gx i_dev_dojo $i
set i ''; set -gx i_dev_django $i
set i ''; set -gx i_dev_npm $i
set i ''; set -gx i_dev_ghost $i
set i ''; set -gx i_dev_modernizr $i
set i ''; set -gx i_dev_unity_small $i
set i ''; set -gx i_dev_rasberry_pi $i
set i ''; set -gx i_dev_blackberry $i
set i ''; set -gx i_dev_go $i
set i ''; set -gx i_dev_git_branch $i
set i ''; set -gx i_dev_git_pull_request $i
set i ''; set -gx i_dev_git_merge $i
set i ''; set -gx i_dev_git_compare $i
set i ''; set -gx i_dev_git_commit $i
set i ''; set -gx i_dev_cssdeck $i
set i ''; set -gx i_dev_yahoo_small $i
set i ''; set -gx i_dev_techcrunch $i
set i ''; set -gx i_dev_smashing_magazine $i
set i ''; set -gx i_dev_netmagazine $i
set i ''; set -gx i_dev_codrops $i
set i ''; set -gx i_dev_phonegap $i
set i ''; set -gx i_dev_google_drive $i
set i ''; set -gx i_dev_html5_multimedia $i
set i ''; set -gx i_dev_html5_device_access $i
set i ''; set -gx i_dev_html5_connectivity $i
set i ''; set -gx i_dev_html5_3d_effects $i
set i ''; set -gx i_dev_html5 $i
set i ''; set -gx i_dev_scala $i
set i ''; set -gx i_dev_java $i
set i ''; set -gx i_dev_ruby $i
set i ''; set -gx i_dev_ubuntu $i
set i ''; set -gx i_dev_ruby_on_rails $i
set i ''; set -gx i_dev_python $i
set i ''; set -gx i_dev_php $i
set i ''; set -gx i_dev_markdown $i
set i ''; set -gx i_dev_laravel $i
set i ''; set -gx i_dev_magento $i
set i ''; set -gx i_dev_joomla $i
set i ''; set -gx i_dev_drupal $i
set i ''; set -gx i_dev_chrome $i
set i ''; set -gx i_dev_ie $i
set i ''; set -gx i_dev_firefox $i
set i ''; set -gx i_dev_opera $i
set i ''; set -gx i_dev_bootstrap $i
set i ''; set -gx i_dev_safari $i
set i ''; set -gx i_dev_css3 $i
set i ''; set -gx i_dev_css3_full $i
set i ''; set -gx i_dev_sass $i
set i ''; set -gx i_dev_grunt $i
set i ''; set -gx i_dev_bower $i
set i ''; set -gx i_dev_javascript $i
set i ''; set -gx i_dev_javascript_shield $i
set i ''; set -gx i_dev_jquery $i
set i ''; set -gx i_dev_coffeescript $i
set i ''; set -gx i_dev_backbone $i
set i ''; set -gx i_dev_angular $i
set i ''; set -gx i_dev_jquery_ui $i
set i ''; set -gx i_dev_swift $i
set i ''; set -gx i_dev_symfony $i
set i ''; set -gx i_dev_symfony_badge $i
set i ''; set -gx i_dev_less $i
set i ''; set -gx i_dev_stylus $i
set i ''; set -gx i_dev_trello $i
set i ''; set -gx i_dev_atlassian $i
set i ''; set -gx i_dev_jira $i
set i ''; set -gx i_dev_envato $i
set i ''; set -gx i_dev_snap_svg $i
set i ''; set -gx i_dev_raphael $i
set i ''; set -gx i_dev_chart $i
set i ''; set -gx i_dev_compass $i
set i ''; set -gx i_dev_onedrive $i
set i ''; set -gx i_dev_gulp $i
set i ''; set -gx i_dev_atom $i
set i ''; set -gx i_dev_cisco $i
set i ''; set -gx i_dev_nancy $i
set i ''; set -gx i_dev_jenkins $i
set i ''; set -gx i_dev_clojure $i
set i ''; set -gx i_dev_perl $i
set i ''; set -gx i_dev_clojure_alt $i
set i ''; set -gx i_dev_celluloid $i
set i ''; set -gx i_dev_w3c $i
set i ''; set -gx i_dev_redis $i
set i ''; set -gx i_dev_postgresql $i
set i ''; set -gx i_dev_webplatform $i
set i ''; set -gx i_dev_requirejs $i
set i ''; set -gx i_dev_opensource $i
set i ''; set -gx i_dev_typo3 $i
set i ''; set -gx i_dev_uikit $i
set i ''; set -gx i_dev_doctrine $i
set i ''; set -gx i_dev_groovy $i
set i ''; set -gx i_dev_nginx $i
set i ''; set -gx i_dev_haskell $i
set i ''; set -gx i_dev_zend $i
set i ''; set -gx i_dev_gnu $i
set i ''; set -gx i_dev_yeoman $i
set i ''; set -gx i_dev_heroku $i
set i ''; set -gx i_dev_msql_server $i
set i ''; set -gx i_dev_debian $i
set i ''; set -gx i_dev_travis $i
set i ''; set -gx i_dev_dotnet $i
set i ''; set -gx i_dev_codeigniter $i
set i ''; set -gx i_dev_javascript_badge $i
set i ''; set -gx i_dev_yii $i
set i ''; set -gx i_dev_composer $i
set i ''; set -gx i_dev_krakenjs_badge $i
set i ''; set -gx i_dev_krakenjs $i
set i ''; set -gx i_dev_mozilla $i
set i ''; set -gx i_dev_firebase $i
set i ''; set -gx i_dev_sizzlejs $i
set i ''; set -gx i_dev_creativecommons $i
set i ''; set -gx i_dev_creativecommons_badge $i
set i ''; set -gx i_dev_mitlicence $i
set i ''; set -gx i_dev_senchatouch $i
set i ''; set -gx i_dev_bugsense $i
set i ''; set -gx i_dev_extjs $i
set i ''; set -gx i_dev_mootools_badge $i
set i ''; set -gx i_dev_mootools $i
set i ''; set -gx i_dev_ruby_rough $i
set i ''; set -gx i_dev_komodo $i
set i ''; set -gx i_dev_coda $i
set i ''; set -gx i_dev_bintray $i
set i ''; set -gx i_dev_terminal $i
set i ''; set -gx i_dev_code $i
set i ''; set -gx i_dev_responsive $i
set i ''; set -gx i_dev_dart $i
set i ''; set -gx i_dev_aptana $i
set i ''; set -gx i_dev_mailchimp $i
set i ''; set -gx i_dev_netbeans $i
set i ''; set -gx i_dev_dreamweaver $i
set i ''; set -gx i_dev_brackets $i
set i ''; set -gx i_dev_eclipse $i
set i ''; set -gx i_dev_cloud9 $i
set i ''; set -gx i_dev_scrum $i
set i ''; set -gx i_dev_prolog $i
set i ''; set -gx i_dev_terminal_badge $i
set i ''; set -gx i_dev_code_badge $i
set i ''; set -gx i_dev_mongodb $i
set i ''; set -gx i_dev_meteor $i
set i ''; set -gx i_dev_meteorfull $i
set i ''; set -gx i_dev_fsharp $i
set i ''; set -gx i_dev_rust $i
set i ''; set -gx i_dev_ionic $i
set i ''; set -gx i_dev_sublime $i
set i ''; set -gx i_dev_appcelerator $i
set i ''; set -gx i_dev_asterisk $i
set i ''; set -gx i_dev_aws $i
set i ''; set -gx i_dev_digital_ocean $i
set i ''; set -gx i_dev_dlang $i
set i ''; set -gx i_dev_docker $i
set i ''; set -gx i_dev_erlang $i
set i ''; set -gx i_dev_google_cloud_platform $i
set i ''; set -gx i_dev_grails $i
set i ''; set -gx i_dev_illustrator $i
set i ''; set -gx i_dev_intellij $i
set i ''; set -gx i_dev_materializecss $i
set i ''; set -gx i_dev_openshift $i
set i ''; set -gx i_dev_photoshop $i
set i ''; set -gx i_dev_rackspace $i
set i ''; set -gx i_dev_react $i
set i ''; set -gx i_dev_redhat $i
set i ''; set -gx i_dev_scriptcs $i
set i ''
set i ''
set i ''
set i ''
set i ''
set i ''
set i ''
set i ''; set -gx i_dev_sqllite $i
set i ''; set -gx i_dev_vim $i

