# Font Awesome Extension (170 icons)
# Codepoints: Nerd Fonts moved E000-E0A9 → E200-E2A9
set i ''; set -gx i_fae_smaller $i
set i ''; set -gx i_fae_snowing $i
set i ''; set -gx i_fae_soda $i
set i ''; set -gx i_fae_sofa $i
set i ''; set -gx i_fae_soup $i
set i ''; set -gx i_fae_spermatozoon $i
set i ''; set -gx i_fae_spin_double $i
set i ''; set -gx i_fae_stomach $i
set i ''; set -gx i_fae_storm $i
set i ''; set -gx i_fae_telescope $i
set i ''; set -gx i_fae_thermometer $i
set i ''; set -gx i_fae_thermometer_high $i
set i ''; set -gx i_fae_thermometer_low $i
set i ''; set -gx i_fae_thin_close $i
set i ''; set -gx i_fae_toilet $i
set i ''; set -gx i_fae_tools $i
set i ''; set -gx i_fae_tooth $i
set i ''; set -gx i_fae_uterus $i
set i ''; set -gx i_fae_w3c $i
set i ''; set -gx i_fae_walking $i
set i ''; set -gx i_fae_virus $i
set i ''; set -gx i_fae_telegram_circle $i
set i ''; set -gx i_fae_slash $i
set i ''; set -gx i_fae_telegram $i
set i ''; set -gx i_fae_shirt $i
set i ''; set -gx i_fae_tacos $i
set i ''; set -gx i_fae_sushi $i
set i ''; set -gx i_fae_triangle_ruler $i
set i ''; set -gx i_fae_tree $i
set i ''; set -gx i_fae_sun_cloud $i
set i ''; set -gx i_fae_ruby_o $i
set i ''; set -gx i_fae_ruler $i
set i ''; set -gx i_fae_umbrella $i
set i ''; set -gx i_fae_medicine $i
set i ''; set -gx i_fae_microscope $i
set i ''; set -gx i_fae_milk_bottle $i
set i ''; set -gx i_fae_minimize $i
set i ''; set -gx i_fae_molecule $i
set i ''; set -gx i_fae_moon_cloud $i
set i ''; set -gx i_fae_mushroom $i
set i ''; set -gx i_fae_mustache $i
set i ''; set -gx i_fae_mysql $i
set i ''; set -gx i_fae_nintendo $i
set i ''; set -gx i_fae_palette_color $i
set i ''; set -gx i_fae_pi $i
set i ''; set -gx i_fae_pizza $i
set i ''; set -gx i_fae_planet $i
set i ''; set -gx i_fae_plant $i
set i ''; set -gx i_fae_playstation $i
set i ''; set -gx i_fae_poison $i
set i ''; set -gx i_fae_popcorn $i
set i ''; set -gx i_fae_popsicle $i
set i ''; set -gx i_fae_pulse $i
set i ''; set -gx i_fae_python $i
set i ''; set -gx i_fae_quora_circle $i
set i ''; set -gx i_fae_quora_square $i
set i ''; set -gx i_fae_radioactive $i
set i ''; set -gx i_fae_raining $i
set i ''; set -gx i_fae_real_heart $i
set i ''; set -gx i_fae_refrigerator $i
set i ''; set -gx i_fae_restore $i
set i ''; set -gx i_fae_ring $i
set i ''; set -gx i_fae_ruby $i
set i ''; set -gx i_fae_fingerprint $i
set i ''; set -gx i_fae_floppy $i
set i ''; set -gx i_fae_footprint $i
set i ''; set -gx i_fae_freecodecamp $i
set i ''; set -gx i_fae_galaxy $i
set i ''; set -gx i_fae_galery $i
set i ''; set -gx i_fae_glass $i
set i ''; set -gx i_fae_google_drive $i
set i ''; set -gx i_fae_google_play $i
set i ''; set -gx i_fae_gps $i
set i ''; set -gx i_fae_grav $i
set i ''; set -gx i_fae_guitar $i
set i ''; set -gx i_fae_gut $i
set i ''; set -gx i_fae_halter $i
set i ''; set -gx i_fae_hamburger $i
set i ''; set -gx i_fae_hat $i
set i ''; set -gx i_fae_hexagon $i
set i ''; set -gx i_fae_high_heel $i
set i ''; set -gx i_fae_hotdog $i
set i ''; set -gx i_fae_ice_cream $i
set i ''; set -gx i_fae_id_card $i
set i ''; set -gx i_fae_imdb $i
set i ''; set -gx i_fae_infinity $i
set i ''; set -gx i_fae_java $i
set i ''; set -gx i_fae_layers $i
set i ''; set -gx i_fae_lips $i
set i ''; set -gx i_fae_lipstick $i
set i ''; set -gx i_fae_liver $i
set i ''; set -gx i_fae_lung $i
set i ''; set -gx i_fae_makeup_brushes $i
set i ''; set -gx i_fae_maximize $i
set i ''; set -gx i_fae_wallet $i
set i ''; set -gx i_fae_chess_horse $i
set i ''; set -gx i_fae_chess_king $i
set i ''; set -gx i_fae_chess_pawn $i
set i ''; set -gx i_fae_chess_queen $i
set i ''; set -gx i_fae_chess_tower $i
set i ''; set -gx i_fae_chesse $i
set i ''; set -gx i_fae_chilli $i
set i ''; set -gx i_fae_chip $i
set i ''; set -gx i_fae_cicling $i
set i ''; set -gx i_fae_cloud $i
set i ''; set -gx i_fae_cockroach $i
set i ''; set -gx i_fae_coffe_beans $i
set i ''; set -gx i_fae_coins $i
set i ''; set -gx i_fae_comb $i
set i ''; set -gx i_fae_comet $i
set i ''; set -gx i_fae_crown $i
set i ''; set -gx i_fae_cup_coffe $i
set i ''; set -gx i_fae_dice $i
set i ''; set -gx i_fae_disco $i
set i ''; set -gx i_fae_dna $i
set i ''; set -gx i_fae_donut $i
set i ''; set -gx i_fae_dress $i
set i ''; set -gx i_fae_drop $i
set i ''; set -gx i_fae_ello $i
set i ''; set -gx i_fae_envelope_open $i
set i ''; set -gx i_fae_envelope_open_o $i
set i ''; set -gx i_fae_equal $i
set i ''; set -gx i_fae_equal_bigger $i
set i ''; set -gx i_fae_feedly $i
set i ''; set -gx i_fae_file_export $i
set i ''; set -gx i_fae_file_import $i
set i ''; set -gx i_fae_wind $i
set i ''; set -gx i_fae_atom $i
set i ''; set -gx i_fae_bacteria $i
set i ''; set -gx i_fae_banana $i
set i ''; set -gx i_fae_bath $i
set i ''; set -gx i_fae_bed $i
set i ''; set -gx i_fae_benzene $i
set i ''; set -gx i_fae_bigger $i
set i ''; set -gx i_fae_biohazard $i
set i ''; set -gx i_fae_blogger_circle $i
set i ''; set -gx i_fae_blogger_square $i
set i ''; set -gx i_fae_bones $i
set i ''; set -gx i_fae_book_open $i
set i ''; set -gx i_fae_book_open_o $i
set i ''; set -gx i_fae_brain $i
set i ''; set -gx i_fae_bread $i
set i ''; set -gx i_fae_butterfly $i
set i ''; set -gx i_fae_carot $i
set i ''; set -gx i_fae_cc_by $i
set i ''; set -gx i_fae_cc_cc $i
set i ''; set -gx i_fae_cc_nc $i
set i ''; set -gx i_fae_cc_nc_eu $i
set i ''; set -gx i_fae_cc_nc_jp $i
set i ''; set -gx i_fae_cc_nd $i
set i ''; set -gx i_fae_cc_remix $i
set i ''; set -gx i_fae_cc_sa $i
set i ''; set -gx i_fae_cc_share $i
set i ''; set -gx i_fae_cc_zero $i
set i ''; set -gx i_fae_checklist_o $i
set i ''; set -gx i_fae_cherry $i
set i ''; set -gx i_fae_chess_bishop $i
set i ''; set -gx i_fae_xbox $i
set i ''; set -gx i_fae_apple_fruit $i
set i ''; set -gx i_fae_chicken_thigh $i
set i ''; set -gx i_fae_gift_card $i
set i ''; set -gx i_fae_injection $i
set i ''; set -gx i_fae_isle $i
set i ''; set -gx i_fae_lollipop $i
set i ''; set -gx i_fae_loyalty_card $i
set i ''; set -gx i_fae_meat $i
set i ''; set -gx i_fae_mountains $i
set i ''; set -gx i_fae_orange $i
set i ''; set -gx i_fae_peach $i
set i ''; set -gx i_fae_pear $i

