# Material Design Icons (2,119 icons)
# Codepoints: F001, F847, Nerd Fonts moved F500-FD46
# Nerd Fonts Version: 2.0.0
# Script Version 1.0.0
set i ''; set -gx i_mdi_vector_square $i
set i ''; set -gx i_mdi_access_point $i
set i ''; set -gx i_mdi_access_point_network $i
set i ''; set -gx i_mdi_account $i
set i ''; set -gx i_mdi_account_alert $i
set i ''; set -gx i_mdi_account_box $i
set i ''; set -gx i_mdi_account_box_outline $i
set i ''; set -gx i_mdi_account_check $i
set i ''; set -gx i_mdi_account_circle $i
set i ''; set -gx i_mdi_account_convert $i
set i ''; set -gx i_mdi_account_key $i
set i ''; set -gx i_mdi_account_location $i
set i ''; set -gx i_mdi_account_minus $i
set i ''; set -gx i_mdi_account_multiple $i
set i ''; set -gx i_mdi_account_multiple_outline $i
set i ''; set -gx i_mdi_account_multiple_plus $i
set i ''; set -gx i_mdi_account_network $i
set i ''; set -gx i_mdi_account_off $i
set i ''; set -gx i_mdi_account_outline $i
set i ''; set -gx i_mdi_account_plus $i
set i ''; set -gx i_mdi_account_remove $i
set i ''; set -gx i_mdi_account_search $i
set i ''; set -gx i_mdi_account_star $i
set i ''; set -gx i_mdi_orbit $i
set i ''; set -gx i_mdi_account_switch $i
set i ''; set -gx i_mdi_adjust $i
set i ''; set -gx i_mdi_air_conditioner $i
set i ''; set -gx i_mdi_airballoon $i
set i ''; set -gx i_mdi_airplane $i
set i ''; set -gx i_mdi_airplane_off $i
set i ''; set -gx i_mdi_airplay $i
set i ''; set -gx i_mdi_alarm $i
set i ''; set -gx i_mdi_alarm_check $i
set i ''; set -gx i_mdi_alarm_multiple $i
set i ''; set -gx i_mdi_alarm_off $i
set i ''; set -gx i_mdi_alarm_plus $i
set i ''; set -gx i_mdi_album $i
set i ''; set -gx i_mdi_alert $i
set i ''; set -gx i_mdi_alert_box $i
set i ''; set -gx i_mdi_alert_circle $i
set i ''; set -gx i_mdi_alert_octagon $i
set i ''; set -gx i_mdi_alert_outline $i
set i ''; set -gx i_mdi_alpha $i
set i ''; set -gx i_mdi_alphabetical $i
set i ''; set -gx i_mdi_amazon $i
set i ''; set -gx i_mdi_amazon_clouddrive $i
set i ''; set -gx i_mdi_ambulance $i
set i ''; set -gx i_mdi_amplifier $i
set i ''; set -gx i_mdi_anchor $i
set i ''; set -gx i_mdi_android $i
set i ''; set -gx i_mdi_android_debug_bridge $i
set i ''; set -gx i_mdi_android_studio $i
set i ''; set -gx i_mdi_apple $i
set i ''; set -gx i_mdi_apple_finder $i
set i ''; set -gx i_mdi_apple_ios $i
set i ''; set -gx i_mdi_apple_mobileme $i
set i ''; set -gx i_mdi_apple_safari $i
set i ''; set -gx i_mdi_font_awesome $i
set i ''; set -gx i_mdi_apps $i
set i ''; set -gx i_mdi_archive $i
set i ''; set -gx i_mdi_arrange_bring_forward $i
set i ''; set -gx i_mdi_arrange_bring_to_front $i
set i ''; set -gx i_mdi_arrange_send_backward $i
set i ''; set -gx i_mdi_arrange_send_to_back $i
set i ''; set -gx i_mdi_arrow_all $i
set i ''; set -gx i_mdi_arrow_bottom_left $i
set i ''; set -gx i_mdi_arrow_bottom_right $i
set i ''; set -gx i_mdi_arrow_collapse_all $i
set i ''; set -gx i_mdi_arrow_down $i
set i ''; set -gx i_mdi_arrow_down_thick $i
set i ''; set -gx i_mdi_arrow_down_bold_circle $i
set i ''; set -gx i_mdi_arrow_down_bold_circle_outline $i
set i ''; set -gx i_mdi_arrow_down_bold_hexagon_outline $i
set i ''; set -gx i_mdi_arrow_down_drop_circle $i
set i ''; set -gx i_mdi_arrow_down_drop_circle_outline $i
set i ''; set -gx i_mdi_arrow_expand_all $i
set i ''; set -gx i_mdi_arrow_left $i
set i ''; set -gx i_mdi_arrow_left_thick $i
set i ''; set -gx i_mdi_arrow_left_bold_circle $i
set i ''; set -gx i_mdi_arrow_left_bold_circle_outline $i
set i ''; set -gx i_mdi_arrow_left_bold_hexagon_outline $i
set i ''; set -gx i_mdi_arrow_left_drop_circle $i
set i ''; set -gx i_mdi_arrow_left_drop_circle_outline $i
set i ''; set -gx i_mdi_arrow_right $i
set i ''; set -gx i_mdi_arrow_right_thick $i
set i ''; set -gx i_mdi_arrow_right_bold_circle $i
set i ''; set -gx i_mdi_arrow_right_bold_circle_outline $i
set i ''; set -gx i_mdi_arrow_right_bold_hexagon_outline $i
set i ''; set -gx i_mdi_arrow_right_drop_circle $i
set i ''; set -gx i_mdi_arrow_right_drop_circle_outline $i
set i ''; set -gx i_mdi_arrow_top_left $i
set i ''; set -gx i_mdi_arrow_top_right $i
set i ''; set -gx i_mdi_arrow_up $i
set i ''; set -gx i_mdi_arrow_up_thick $i
set i ''; set -gx i_mdi_arrow_up_bold_circle $i
set i ''; set -gx i_mdi_arrow_up_bold_circle_outline $i
set i ''; set -gx i_mdi_arrow_up_bold_hexagon_outline $i
set i ''; set -gx i_mdi_arrow_up_drop_circle $i
set i ''; set -gx i_mdi_arrow_up_drop_circle_outline $i
set i ''; set -gx i_mdi_assistant $i
set i ''; set -gx i_mdi_at $i
set i ''; set -gx i_mdi_attachment $i
set i ''; set -gx i_mdi_audiobook $i
set i ''; set -gx i_mdi_auto_fix $i
set i ''; set -gx i_mdi_auto_upload $i
set i ''; set -gx i_mdi_autorenew $i
set i ''; set -gx i_mdi_av_timer $i
set i ''; set -gx i_mdi_baby $i
set i ''; set -gx i_mdi_backburger $i
set i ''; set -gx i_mdi_backspace $i
set i ''; set -gx i_mdi_backup_restore $i
set i ''; set -gx i_mdi_bank $i
set i ''; set -gx i_mdi_barcode $i
set i ''; set -gx i_mdi_barcode_scan $i
set i ''; set -gx i_mdi_barley $i
set i ''; set -gx i_mdi_barrel $i
set i ''; set -gx i_mdi_basecamp $i
set i ''; set -gx i_mdi_basket $i
set i ''; set -gx i_mdi_basket_fill $i
set i ''; set -gx i_mdi_basket_unfill $i
set i ''; set -gx i_mdi_battery $i
set i ''; set -gx i_mdi_battery_10 $i
set i ''; set -gx i_mdi_battery_20 $i
set i ''; set -gx i_mdi_battery_30 $i
set i ''; set -gx i_mdi_battery_40 $i
set i ''; set -gx i_mdi_battery_50 $i
set i ''; set -gx i_mdi_battery_60 $i
set i ''; set -gx i_mdi_battery_70 $i
set i ''; set -gx i_mdi_battery_80 $i
set i ''; set -gx i_mdi_battery_90 $i
set i ''; set -gx i_mdi_battery_alert $i
set i ''; set -gx i_mdi_battery_charging $i
set i ''; set -gx i_mdi_battery_charging_100 $i
set i ''; set -gx i_mdi_battery_charging_20 $i
set i ''; set -gx i_mdi_battery_charging_30 $i
set i ''; set -gx i_mdi_battery_charging_40 $i
set i ''; set -gx i_mdi_battery_charging_60 $i
set i ''; set -gx i_mdi_battery_charging_80 $i
set i ''; set -gx i_mdi_battery_charging_90 $i
set i ''; set -gx i_mdi_battery_minus $i
set i ''; set -gx i_mdi_battery_negative $i
set i ''; set -gx i_mdi_battery_outline $i
set i ''; set -gx i_mdi_battery_plus $i
set i ''; set -gx i_mdi_battery_positive $i
set i ''; set -gx i_mdi_battery_unknown $i
set i ''; set -gx i_mdi_beach $i
set i ''; set -gx i_mdi_flask $i
set i ''; set -gx i_mdi_flask_empty $i
set i ''; set -gx i_mdi_flask_empty_outline $i
set i ''; set -gx i_mdi_flask_outline $i
set i ''; set -gx i_mdi_beats $i
set i ''; set -gx i_mdi_beer $i
set i ''; set -gx i_mdi_behance $i
set i ''; set -gx i_mdi_bell $i
set i ''; set -gx i_mdi_bell_off $i
set i ''; set -gx i_mdi_bell_outline $i
set i ''; set -gx i_mdi_bell_plus $i
set i ''; set -gx i_mdi_bell_ring $i
set i ''; set -gx i_mdi_bell_ring_outline $i
set i ''; set -gx i_mdi_bell_sleep $i
set i ''; set -gx i_mdi_beta $i
set i ''; set -gx i_mdi_bible $i
set i ''; set -gx i_mdi_bike $i
set i ''; set -gx i_mdi_bing $i
set i ''; set -gx i_mdi_binoculars $i
set i ''; set -gx i_mdi_bio $i
set i ''; set -gx i_mdi_biohazard $i
set i ''; set -gx i_mdi_bitbucket $i
set i ''; set -gx i_mdi_black_mesa $i
set i ''; set -gx i_mdi_blackberry $i
set i ''; set -gx i_mdi_blender $i
set i ''; set -gx i_mdi_blinds $i
set i ''; set -gx i_mdi_block_helper $i
set i ''; set -gx i_mdi_blogger $i
set i ''; set -gx i_mdi_bluetooth $i
set i ''; set -gx i_mdi_bluetooth_audio $i
set i ''; set -gx i_mdi_bluetooth_connect $i
set i ''; set -gx i_mdi_bluetooth_off $i
set i ''; set -gx i_mdi_bluetooth_settings $i
set i ''; set -gx i_mdi_bluetooth_transfer $i
set i ''; set -gx i_mdi_blur $i
set i ''; set -gx i_mdi_blur_linear $i
set i ''; set -gx i_mdi_blur_off $i
set i ''; set -gx i_mdi_blur_radial $i
set i ''; set -gx i_mdi_bone $i
set i ''; set -gx i_mdi_book $i
set i ''; set -gx i_mdi_book_multiple $i
set i ''; set -gx i_mdi_book_multiple_variant $i
set i ''; set -gx i_mdi_book_open $i
set i ''; set -gx i_mdi_book_open_variant $i
set i ''; set -gx i_mdi_book_variant $i
set i ''; set -gx i_mdi_bookmark $i
set i ''; set -gx i_mdi_bookmark_check $i
set i ''; set -gx i_mdi_bookmark_music $i
set i ''; set -gx i_mdi_bookmark_outline $i
set i ''; set -gx i_mdi_bookmark_plus_outline $i
set i ''; set -gx i_mdi_bookmark_plus $i
set i ''; set -gx i_mdi_bookmark_remove $i
set i ''; set -gx i_mdi_border_all $i
set i ''; set -gx i_mdi_border_bottom $i
set i ''; set -gx i_mdi_border_color $i
set i ''; set -gx i_mdi_border_horizontal $i
set i ''; set -gx i_mdi_border_inside $i
set i ''; set -gx i_mdi_border_left $i
set i ''; set -gx i_mdi_border_none $i
set i ''; set -gx i_mdi_border_outside $i
set i ''; set -gx i_mdi_border_right $i
set i ''; set -gx i_mdi_border_style $i
set i ''; set -gx i_mdi_border_top $i
set i ''; set -gx i_mdi_border_vertical $i
set i ''; set -gx i_mdi_bowling $i
set i ''; set -gx i_mdi_box $i
set i ''; set -gx i_mdi_box_cutter $i
set i ''; set -gx i_mdi_briefcase $i
set i ''; set -gx i_mdi_briefcase_check $i
set i ''; set -gx i_mdi_briefcase_download $i
set i ''; set -gx i_mdi_briefcase_upload $i
set i ''; set -gx i_mdi_brightness_1 $i
set i ''; set -gx i_mdi_brightness_2 $i
set i ''; set -gx i_mdi_brightness_3 $i
set i ''; set -gx i_mdi_brightness_4 $i
set i ''; set -gx i_mdi_brightness_5 $i
set i ''; set -gx i_mdi_brightness_6 $i
set i ''; set -gx i_mdi_brightness_7 $i
set i ''; set -gx i_mdi_brightness_auto $i
set i ''; set -gx i_mdi_broom $i
set i ''; set -gx i_mdi_brush $i
set i ''; set -gx i_mdi_bug $i
set i ''; set -gx i_mdi_bulletin_board $i
set i ''; set -gx i_mdi_bullhorn $i
set i ''; set -gx i_mdi_bus $i
set i ''; set -gx i_mdi_cached $i
set i ''; set -gx i_mdi_cake $i
set i ''; set -gx i_mdi_cake_layered $i
set i ''; set -gx i_mdi_cake_variant $i
set i ''; set -gx i_mdi_calculator $i
set i ''; set -gx i_mdi_calendar $i
set i ''; set -gx i_mdi_calendar_blank $i
set i ''; set -gx i_mdi_calendar_check $i
set i ''; set -gx i_mdi_calendar_clock $i
set i ''; set -gx i_mdi_calendar_multiple $i
set i ''; set -gx i_mdi_calendar_multiple_check $i
set i ''; set -gx i_mdi_calendar_plus $i
set i ''; set -gx i_mdi_calendar_remove $i
set i ''; set -gx i_mdi_calendar_text $i
set i ''; set -gx i_mdi_calendar_today $i
set i ''; set -gx i_mdi_call_made $i
set i ''; set -gx i_mdi_call_merge $i
set i ''; set -gx i_mdi_call_missed $i
set i ''; set -gx i_mdi_call_received $i
set i ''; set -gx i_mdi_call_split $i
set i ''; set -gx i_mdi_camcorder $i
set i ''; set -gx i_mdi_camcorder_box $i
set i ''; set -gx i_mdi_camcorder_box_off $i
set i ''; set -gx i_mdi_camcorder_off $i
set i ''; set -gx i_mdi_camera $i
set i ''; set -gx i_mdi_camera_enhance $i
set i ''; set -gx i_mdi_camera_front $i
set i ''; set -gx i_mdi_camera_front_variant $i
set i ''; set -gx i_mdi_camera_iris $i
set i ''; set -gx i_mdi_camera_party_mode $i
set i ''; set -gx i_mdi_camera_rear $i
set i ''; set -gx i_mdi_camera_rear_variant $i
set i ''; set -gx i_mdi_camera_switch $i
set i ''; set -gx i_mdi_camera_timer $i
set i ''; set -gx i_mdi_candycane $i
set i ''; set -gx i_mdi_car $i
set i ''; set -gx i_mdi_car_battery $i
set i ''; set -gx i_mdi_car_connected $i
set i ''; set -gx i_mdi_car_wash $i
set i ''; set -gx i_mdi_carrot $i
set i ''; set -gx i_mdi_cart $i
set i ''; set -gx i_mdi_cart_outline $i
set i ''; set -gx i_mdi_cart_plus $i
set i ''; set -gx i_mdi_case_sensitive_alt $i
set i ''; set -gx i_mdi_cash $i
set i ''; set -gx i_mdi_cash_100 $i
set i ''; set -gx i_mdi_cash_multiple $i
set i ''; set -gx i_mdi_cash_usd $i
set i ''; set -gx i_mdi_cast $i
set i ''; set -gx i_mdi_cast_connected $i
set i ''; set -gx i_mdi_castle $i
set i ''; set -gx i_mdi_cat $i
set i ''; set -gx i_mdi_cellphone $i
set i ''; set -gx i_mdi_cellphone_android $i
set i ''; set -gx i_mdi_cellphone_basic $i
set i ''; set -gx i_mdi_cellphone_dock $i
set i ''; set -gx i_mdi_cellphone_iphone $i
set i ''; set -gx i_mdi_cellphone_link $i
set i ''; set -gx i_mdi_cellphone_link_off $i
set i ''; set -gx i_mdi_cellphone_settings $i
set i ''; set -gx i_mdi_certificate $i
set i ''; set -gx i_mdi_chair_school $i
set i ''; set -gx i_mdi_chart_arc $i
set i ''; set -gx i_mdi_chart_areaspline $i
set i ''; set -gx i_mdi_chart_bar $i
set i ''; set -gx i_mdi_chart_histogram $i
set i ''; set -gx i_mdi_chart_line $i
set i ''; set -gx i_mdi_chart_pie $i
set i ''; set -gx i_mdi_check $i
set i ''; set -gx i_mdi_check_all $i
set i ''; set -gx i_mdi_checkbox_blank $i
set i ''; set -gx i_mdi_checkbox_blank_circle $i
set i ''; set -gx i_mdi_checkbox_blank_circle_outline $i
set i ''; set -gx i_mdi_checkbox_blank_outline $i
set i ''; set -gx i_mdi_checkbox_marked $i
set i ''; set -gx i_mdi_checkbox_marked_circle $i
set i ''; set -gx i_mdi_checkbox_marked_circle_outline $i
set i ''; set -gx i_mdi_checkbox_marked_outline $i
set i ''; set -gx i_mdi_checkbox_multiple_blank $i
set i ''; set -gx i_mdi_checkbox_multiple_blank_outline $i
set i ''; set -gx i_mdi_checkbox_multiple_marked $i
set i ''; set -gx i_mdi_checkbox_multiple_marked_outline $i
set i ''; set -gx i_mdi_checkerboard $i
set i ''; set -gx i_mdi_chemical_weapon $i
set i ''; set -gx i_mdi_chevron_double_down $i
set i ''; set -gx i_mdi_chevron_double_left $i
set i ''; set -gx i_mdi_chevron_double_right $i
set i ''; set -gx i_mdi_chevron_double_up $i
set i ''; set -gx i_mdi_chevron_down $i
set i ''; set -gx i_mdi_chevron_left $i
set i ''; set -gx i_mdi_chevron_right $i
set i ''; set -gx i_mdi_chevron_up $i
set i ''; set -gx i_mdi_church $i
set i ''; set -gx i_mdi_cisco_webex $i
set i ''; set -gx i_mdi_city $i
set i ''; set -gx i_mdi_clipboard $i
set i ''; set -gx i_mdi_clipboard_account $i
set i ''; set -gx i_mdi_clipboard_alert $i
set i ''; set -gx i_mdi_clipboard_arrow_down $i
set i ''; set -gx i_mdi_clipboard_arrow_left $i
set i ''; set -gx i_mdi_clipboard_check $i
set i ''; set -gx i_mdi_clipboard_outline $i
set i ''; set -gx i_mdi_clipboard_text $i
set i ''; set -gx i_mdi_clippy $i
set i ''; set -gx i_mdi_clock $i
set i ''; set -gx i_mdi_clock_end $i
set i ''; set -gx i_mdi_clock_fast $i
set i ''; set -gx i_mdi_clock_in $i
set i ''; set -gx i_mdi_clock_out $i
set i ''; set -gx i_mdi_clock_start $i
set i ''; set -gx i_mdi_close $i
set i ''; set -gx i_mdi_close_box $i
set i ''; set -gx i_mdi_close_box_outline $i
set i ''; set -gx i_mdi_close_circle $i
set i ''; set -gx i_mdi_close_circle_outline $i
set i ''; set -gx i_mdi_close_network $i
set i ''; set -gx i_mdi_close_octagon $i
set i ''; set -gx i_mdi_close_octagon_outline $i
set i ''; set -gx i_mdi_closed_caption $i
set i ''; set -gx i_mdi_cloud $i
set i ''; set -gx i_mdi_cloud_check $i
set i ''; set -gx i_mdi_cloud_circle $i
set i ''; set -gx i_mdi_cloud_download $i
set i ''; set -gx i_mdi_cloud_outline $i
set i ''; set -gx i_mdi_cloud_off_outline $i
set i ''; set -gx i_mdi_cloud_print $i
set i ''; set -gx i_mdi_cloud_print_outline $i
set i ''; set -gx i_mdi_cloud_upload $i
set i ''; set -gx i_mdi_code_array $i
set i ''; set -gx i_mdi_code_braces $i
set i ''; set -gx i_mdi_code_brackets $i
set i ''; set -gx i_mdi_code_equal $i
set i ''; set -gx i_mdi_code_greater_than $i
set i ''; set -gx i_mdi_code_greater_than_or_equal $i
set i ''; set -gx i_mdi_code_less_than $i
set i ''; set -gx i_mdi_code_less_than_or_equal $i
set i ''; set -gx i_mdi_code_not_equal $i
set i ''; set -gx i_mdi_code_not_equal_variant $i
set i ''; set -gx i_mdi_code_parentheses $i
set i ''; set -gx i_mdi_code_string $i
set i ''; set -gx i_mdi_code_tags $i
set i ''; set -gx i_mdi_codepen $i
set i ''; set -gx i_mdi_coffee $i
set i ''; set -gx i_mdi_coffee_to_go $i
set i ''; set -gx i_mdi_coin $i
set i ''; set -gx i_mdi_color_helper $i
set i ''; set -gx i_mdi_comment $i
set i ''; set -gx i_mdi_comment_account $i
set i ''; set -gx i_mdi_comment_account_outline $i
set i ''; set -gx i_mdi_comment_alert $i
set i ''; set -gx i_mdi_comment_alert_outline $i
set i ''; set -gx i_mdi_comment_check $i
set i ''; set -gx i_mdi_comment_check_outline $i
set i ''; set -gx i_mdi_comment_multiple_outline $i
set i ''; set -gx i_mdi_comment_outline $i
set i ''; set -gx i_mdi_comment_plus_outline $i
set i ''; set -gx i_mdi_comment_processing $i
set i ''; set -gx i_mdi_comment_processing_outline $i
set i ''; set -gx i_mdi_comment_question_outline $i
set i ''; set -gx i_mdi_comment_remove_outline $i
set i ''; set -gx i_mdi_comment_text $i
set i ''; set -gx i_mdi_comment_text_outline $i
set i ''; set -gx i_mdi_compare $i
set i ''; set -gx i_mdi_compass $i
set i ''; set -gx i_mdi_compass_outline $i
set i ''; set -gx i_mdi_console $i
set i ''; set -gx i_mdi_contact_mail $i
set i ''; set -gx i_mdi_content_copy $i
set i ''; set -gx i_mdi_content_cut $i
set i ''; set -gx i_mdi_content_duplicate $i
set i ''; set -gx i_mdi_content_paste $i
set i ''; set -gx i_mdi_content_save $i
set i ''; set -gx i_mdi_content_save_all $i
set i ''; set -gx i_mdi_contrast $i
set i ''; set -gx i_mdi_contrast_box $i
set i ''; set -gx i_mdi_contrast_circle $i
set i ''; set -gx i_mdi_cookie $i
set i ''; set -gx i_mdi_counter $i
set i ''; set -gx i_mdi_cow $i
set i ''; set -gx i_mdi_credit_card $i
set i ''; set -gx i_mdi_credit_card_multiple $i
set i ''; set -gx i_mdi_credit_card_scan $i
set i ''; set -gx i_mdi_crop $i
set i ''; set -gx i_mdi_crop_free $i
set i ''; set -gx i_mdi_crop_landscape $i
set i ''; set -gx i_mdi_crop_portrait $i
set i ''; set -gx i_mdi_crop_square $i
set i ''; set -gx i_mdi_crosshairs $i
set i ''; set -gx i_mdi_crosshairs_gps $i
set i ''; set -gx i_mdi_crown $i
set i ''; set -gx i_mdi_cube $i
set i ''; set -gx i_mdi_cube_outline $i
set i ''; set -gx i_mdi_cube_send $i
set i ''; set -gx i_mdi_cube_unfolded $i
set i ''; set -gx i_mdi_cup $i
set i ''; set -gx i_mdi_cup_water $i
set i ''; set -gx i_mdi_currency_btc $i
set i ''; set -gx i_mdi_currency_eur $i
set i ''; set -gx i_mdi_currency_gbp $i
set i ''; set -gx i_mdi_currency_inr $i
set i ''; set -gx i_mdi_currency_ngn $i
set i ''; set -gx i_mdi_currency_rub $i
set i ''; set -gx i_mdi_currency_try $i
set i ''; set -gx i_mdi_currency_usd $i
set i ''; set -gx i_mdi_cursor_default $i
set i ''; set -gx i_mdi_cursor_default_outline $i
set i ''; set -gx i_mdi_cursor_move $i
set i ''; set -gx i_mdi_cursor_pointer $i
set i ''; set -gx i_mdi_database $i
set i ''; set -gx i_mdi_database_minus $i
set i ''; set -gx i_mdi_database_plus $i
set i ''; set -gx i_mdi_debug_step_into $i
set i ''; set -gx i_mdi_debug_step_out $i
set i ''; set -gx i_mdi_debug_step_over $i
set i ''; set -gx i_mdi_decimal_decrease $i
set i ''; set -gx i_mdi_decimal_increase $i
set i ''; set -gx i_mdi_delete $i
set i ''; set -gx i_mdi_delete_variant $i
set i ''; set -gx i_mdi_delta $i
set i ''; set -gx i_mdi_deskphone $i
set i ''; set -gx i_mdi_desktop_mac $i
set i ''; set -gx i_mdi_desktop_tower $i
set i ''; set -gx i_mdi_details $i
set i ''; set -gx i_mdi_deviantart $i
set i ''; set -gx i_mdi_diamond $i
set i ''; set -gx i_mdi_creation $i
set i ''; set -gx i_mdi_dice_1 $i
set i ''; set -gx i_mdi_dice_2 $i
set i ''; set -gx i_mdi_dice_3 $i
set i ''; set -gx i_mdi_dice_4 $i
set i ''; set -gx i_mdi_dice_5 $i
set i ''; set -gx i_mdi_dice_6 $i
set i ''; set -gx i_mdi_directions $i
set i ''; set -gx i_mdi_disk_alert $i
set i ''; set -gx i_mdi_disqus $i
set i ''; set -gx i_mdi_disqus_outline $i
set i ''; set -gx i_mdi_division $i
set i ''; set -gx i_mdi_division_box $i
set i ''; set -gx i_mdi_dns $i
set i ''; set -gx i_mdi_domain $i
set i ''; set -gx i_mdi_dots_horizontal $i
set i ''; set -gx i_mdi_dots_vertical $i
set i ''; set -gx i_mdi_download $i
set i ''; set -gx i_mdi_drag $i
set i ''; set -gx i_mdi_drag_horizontal $i
set i ''; set -gx i_mdi_drag_vertical $i
set i ''; set -gx i_mdi_drawing $i
set i ''; set -gx i_mdi_drawing_box $i
set i ''; set -gx i_mdi_dribbble $i
set i ''; set -gx i_mdi_dribbble_box $i
set i ''; set -gx i_mdi_drone $i
set i ''; set -gx i_mdi_dropbox $i
set i ''; set -gx i_mdi_drupal $i
set i ''; set -gx i_mdi_duck $i
set i ''; set -gx i_mdi_dumbbell $i
set i ''; set -gx i_mdi_earth $i
set i ''; set -gx i_mdi_earth_off $i
set i ''; set -gx i_mdi_edge $i
set i ''; set -gx i_mdi_eject $i
set i ''; set -gx i_mdi_elevation_decline $i
set i ''; set -gx i_mdi_elevation_rise $i
set i ''; set -gx i_mdi_elevator $i
set i ''; set -gx i_mdi_email $i
set i ''; set -gx i_mdi_email_open $i
set i ''; set -gx i_mdi_email_outline $i
set i ''; set -gx i_mdi_email_secure $i
set i ''; set -gx i_mdi_emoticon $i
set i ''; set -gx i_mdi_emoticon_cool $i
set i ''; set -gx i_mdi_emoticon_devil $i
set i ''; set -gx i_mdi_emoticon_happy $i
set i ''; set -gx i_mdi_emoticon_neutral $i
set i ''; set -gx i_mdi_emoticon_poop $i
set i ''; set -gx i_mdi_emoticon_sad $i
set i ''; set -gx i_mdi_emoticon_tongue $i
set i ''; set -gx i_mdi_engine $i
set i ''; set -gx i_mdi_engine_outline $i
set i ''; set -gx i_mdi_equal $i
set i ''; set -gx i_mdi_equal_box $i
set i ''; set -gx i_mdi_eraser $i
set i ''; set -gx i_mdi_escalator $i
set i ''; set -gx i_mdi_ethernet $i
set i ''; set -gx i_mdi_ethernet_cable $i
set i ''; set -gx i_mdi_ethernet_cable_off $i
set i ''; set -gx i_mdi_etsy $i
set i ''; set -gx i_mdi_evernote $i
set i ''; set -gx i_mdi_exclamation $i
set i ''; set -gx i_mdi_exit_to_app $i
set i ''; set -gx i_mdi_export $i
set i ''; set -gx i_mdi_eye $i
set i ''; set -gx i_mdi_eye_off $i
set i ''; set -gx i_mdi_eyedropper $i
set i ''; set -gx i_mdi_eyedropper_variant $i
set i ''; set -gx i_mdi_facebook $i
set i ''; set -gx i_mdi_facebook_box $i
set i ''; set -gx i_mdi_facebook_messenger $i
set i ''; set -gx i_mdi_factory $i
set i ''; set -gx i_mdi_fan $i
set i ''; set -gx i_mdi_fast_forward $i
set i ''; set -gx i_mdi_fax $i
set i ''; set -gx i_mdi_ferry $i
set i ''; set -gx i_mdi_file $i
set i ''; set -gx i_mdi_file_chart $i
set i ''; set -gx i_mdi_file_check $i
set i ''; set -gx i_mdi_file_cloud $i
set i ''; set -gx i_mdi_file_delimited $i
set i ''; set -gx i_mdi_file_document $i
set i ''; set -gx i_mdi_file_document_box $i
set i ''; set -gx i_mdi_file_excel $i
set i ''; set -gx i_mdi_file_excel_box $i
set i ''; set -gx i_mdi_file_export $i
set i ''; set -gx i_mdi_file_find $i
set i ''; set -gx i_mdi_file_image $i
set i ''; set -gx i_mdi_file_import $i
set i ''; set -gx i_mdi_file_lock $i
set i ''; set -gx i_mdi_file_multiple $i
set i ''; set -gx i_mdi_file_music $i
set i ''; set -gx i_mdi_file_outline $i
set i ''; set -gx i_mdi_file_pdf $i
set i ''; set -gx i_mdi_file_pdf_box $i
set i ''; set -gx i_mdi_file_powerpoint $i
set i ''; set -gx i_mdi_file_powerpoint_box $i
set i ''; set -gx i_mdi_file_presentation_box $i
set i ''; set -gx i_mdi_file_send $i
set i ''; set -gx i_mdi_file_video $i
set i ''; set -gx i_mdi_file_word $i
set i ''; set -gx i_mdi_file_word_box $i
set i ''; set -gx i_mdi_file_xml $i
set i ''; set -gx i_mdi_film $i
set i ''; set -gx i_mdi_filmstrip $i
set i ''; set -gx i_mdi_filmstrip_off $i
set i ''; set -gx i_mdi_filter $i
set i ''; set -gx i_mdi_filter_outline $i
set i ''; set -gx i_mdi_filter_remove $i
set i ''; set -gx i_mdi_filter_remove_outline $i
set i ''; set -gx i_mdi_filter_variant $i
set i ''; set -gx i_mdi_fingerprint $i
set i ''; set -gx i_mdi_fire $i
set i ''; set -gx i_mdi_firefox $i
set i ''; set -gx i_mdi_fish $i
set i ''; set -gx i_mdi_flag $i
set i ''; set -gx i_mdi_flag_checkered $i
set i ''; set -gx i_mdi_flag_outline $i
set i ''; set -gx i_mdi_flag_variant_outline $i
set i ''; set -gx i_mdi_flag_triangle $i
set i ''; set -gx i_mdi_flag_variant $i
set i ''; set -gx i_mdi_flash $i
set i ''; set -gx i_mdi_flash_auto $i
set i ''; set -gx i_mdi_flash_off $i
set i ''; set -gx i_mdi_flashlight $i
set i ''; set -gx i_mdi_flashlight_off $i
set i ''; set -gx i_mdi_flattr $i
set i ''; set -gx i_mdi_flip_to_back $i
set i ''; set -gx i_mdi_flip_to_front $i
set i ''; set -gx i_mdi_floppy $i
set i ''; set -gx i_mdi_flower $i
set i ''; set -gx i_mdi_folder $i
set i ''; set -gx i_mdi_folder_account $i
set i ''; set -gx i_mdi_folder_download $i
set i ''; set -gx i_mdi_folder_google_drive $i
set i ''; set -gx i_mdi_folder_image $i
set i ''; set -gx i_mdi_folder_lock $i
set i ''; set -gx i_mdi_folder_lock_open $i
set i ''; set -gx i_mdi_folder_move $i
set i ''; set -gx i_mdi_folder_multiple $i
set i ''; set -gx i_mdi_folder_multiple_image $i
set i ''; set -gx i_mdi_folder_multiple_outline $i
set i ''; set -gx i_mdi_folder_outline $i
set i ''; set -gx i_mdi_folder_plus $i
set i ''; set -gx i_mdi_folder_remove $i
set i ''; set -gx i_mdi_folder_upload $i
set i ''; set -gx i_mdi_food $i
set i ''; set -gx i_mdi_food_apple $i
set i ''; set -gx i_mdi_food_variant $i
set i ''; set -gx i_mdi_football $i
set i ''; set -gx i_mdi_football_australian $i
set i ''; set -gx i_mdi_football_helmet $i
set i ''; set -gx i_mdi_format_align_center $i
set i ''; set -gx i_mdi_format_align_justify $i
set i ''; set -gx i_mdi_format_align_left $i
set i ''; set -gx i_mdi_format_align_right $i
set i ''; set -gx i_mdi_format_bold $i
set i ''; set -gx i_mdi_format_clear $i
set i ''; set -gx i_mdi_format_color_fill $i
set i ''; set -gx i_mdi_format_float_center $i
set i ''; set -gx i_mdi_format_float_left $i
set i ''; set -gx i_mdi_format_float_none $i
set i ''; set -gx i_mdi_format_float_right $i
set i ''; set -gx i_mdi_format_header_1 $i
set i ''; set -gx i_mdi_format_header_2 $i
set i ''; set -gx i_mdi_format_header_3 $i
set i ''; set -gx i_mdi_format_header_4 $i
set i ''; set -gx i_mdi_format_header_5 $i
set i ''; set -gx i_mdi_format_header_6 $i
set i ''; set -gx i_mdi_format_header_decrease $i
set i ''; set -gx i_mdi_format_header_equal $i
set i ''; set -gx i_mdi_format_header_increase $i
set i ''; set -gx i_mdi_format_header_pound $i
set i ''; set -gx i_mdi_format_indent_decrease $i
set i ''; set -gx i_mdi_format_indent_increase $i
set i ''; set -gx i_mdi_format_italic $i
set i ''; set -gx i_mdi_format_line_spacing $i
set i ''; set -gx i_mdi_format_list_bulleted $i
set i ''; set -gx i_mdi_format_list_bulleted_type $i
set i ''; set -gx i_mdi_format_list_numbers $i
set i ''; set -gx i_mdi_format_paint $i
set i ''; set -gx i_mdi_format_paragraph $i
set i ''; set -gx i_mdi_format_quote_close $i
set i ''; set -gx i_mdi_format_size $i
set i ''; set -gx i_mdi_format_strikethrough $i
set i ''; set -gx i_mdi_format_strikethrough_variant $i
set i ''; set -gx i_mdi_format_subscript $i
set i ''; set -gx i_mdi_format_superscript $i
set i ''; set -gx i_mdi_format_text $i
set i ''; set -gx i_mdi_format_textdirection_l_to_r $i
set i ''; set -gx i_mdi_format_textdirection_r_to_l $i
set i ''; set -gx i_mdi_format_underline $i
set i ''; set -gx i_mdi_format_wrap_inline $i
set i ''; set -gx i_mdi_format_wrap_square $i
set i ''; set -gx i_mdi_format_wrap_tight $i
set i ''; set -gx i_mdi_format_wrap_top_bottom $i
set i ''; set -gx i_mdi_forum $i
set i ''; set -gx i_mdi_forward $i
set i ''; set -gx i_mdi_foursquare $i
set i ''; set -gx i_mdi_fridge $i
set i ''; set -gx i_mdi_fridge_filled $i
set i ''; set -gx i_mdi_fridge_filled_bottom $i
set i ''; set -gx i_mdi_fridge_filled_top $i
set i ''; set -gx i_mdi_fullscreen $i
set i ''; set -gx i_mdi_fullscreen_exit $i
set i ''; set -gx i_mdi_function $i
set i ''; set -gx i_mdi_gamepad $i
set i ''; set -gx i_mdi_gamepad_variant $i
set i ''; set -gx i_mdi_gas_station $i
set i ''; set -gx i_mdi_gate $i
set i ''; set -gx i_mdi_gauge $i
set i ''; set -gx i_mdi_gavel $i
set i ''; set -gx i_mdi_gender_female $i
set i ''; set -gx i_mdi_gender_male $i
set i ''; set -gx i_mdi_gender_male_female $i
set i ''; set -gx i_mdi_gender_transgender $i
set i ''; set -gx i_mdi_ghost $i
set i ''; set -gx i_mdi_gift $i
set i ''; set -gx i_mdi_git $i
set i ''; set -gx i_mdi_github_box $i
set i ''; set -gx i_mdi_github_circle $i
set i ''; set -gx i_mdi_glass_flute $i
set i ''; set -gx i_mdi_glass_mug $i
set i ''; set -gx i_mdi_glass_stange $i
set i ''; set -gx i_mdi_glass_tulip $i
set i ''; set -gx i_mdi_glassdoor $i
set i ''; set -gx i_mdi_glasses $i
set i ''; set -gx i_mdi_gmail $i
set i ''; set -gx i_mdi_gnome $i
set i ''; set -gx i_mdi_google $i
set i ''; set -gx i_mdi_google_cardboard $i
set i ''; set -gx i_mdi_google_chrome $i
set i ''; set -gx i_mdi_google_circles $i
set i ''; set -gx i_mdi_google_circles_communities $i
set i ''; set -gx i_mdi_google_circles_extended $i
set i ''; set -gx i_mdi_google_circles_group $i
set i ''; set -gx i_mdi_google_controller $i
set i ''; set -gx i_mdi_google_controller_off $i
set i ''; set -gx i_mdi_google_drive $i
set i ''; set -gx i_mdi_google_earth $i
set i ''; set -gx i_mdi_google_glass $i
set i ''; set -gx i_mdi_google_nearby $i
set i ''; set -gx i_mdi_google_pages $i
set i ''; set -gx i_mdi_google_physical_web $i
set i ''; set -gx i_mdi_google_play $i
set i ''; set -gx i_mdi_google_plus $i
set i ''; set -gx i_mdi_google_plus_box $i
set i ''; set -gx i_mdi_google_translate $i
set i ''; set -gx i_mdi_google_wallet $i
set i ''; set -gx i_mdi_grid $i
set i ''; set -gx i_mdi_grid_off $i
set i ''; set -gx i_mdi_group $i
set i ''; set -gx i_mdi_guitar_electric $i
set i ''; set -gx i_mdi_guitar_pick $i
set i ''; set -gx i_mdi_guitar_pick_outline $i
set i ''; set -gx i_mdi_hand_pointing_right $i
set i ''; set -gx i_mdi_hanger $i
set i ''; set -gx i_mdi_hangouts $i
set i ''; set -gx i_mdi_harddisk $i
set i ''; set -gx i_mdi_headphones $i
set i ''; set -gx i_mdi_headphones_box $i
set i ''; set -gx i_mdi_headphones_settings $i
set i ''; set -gx i_mdi_headset $i
set i ''; set -gx i_mdi_headset_dock $i
set i ''; set -gx i_mdi_headset_off $i
set i ''; set -gx i_mdi_heart $i
set i ''; set -gx i_mdi_heart_box $i
set i ''; set -gx i_mdi_heart_box_outline $i
set i ''; set -gx i_mdi_heart_broken $i
set i ''; set -gx i_mdi_heart_outline $i
set i ''; set -gx i_mdi_help $i
set i ''; set -gx i_mdi_help_circle $i
set i ''; set -gx i_mdi_hexagon $i
set i ''; set -gx i_mdi_hexagon_outline $i
set i ''; set -gx i_mdi_history $i
set i ''; set -gx i_mdi_hololens $i
set i ''; set -gx i_mdi_home $i
set i ''; set -gx i_mdi_home_modern $i
set i ''; set -gx i_mdi_home_variant $i
set i ''; set -gx i_mdi_hops $i
set i ''; set -gx i_mdi_hospital $i
set i ''; set -gx i_mdi_hospital_building $i
set i ''; set -gx i_mdi_hospital_marker $i
set i ''; set -gx i_mdi_hotel $i
set i ''; set -gx i_mdi_houzz $i
set i ''; set -gx i_mdi_houzz_box $i
set i ''; set -gx i_mdi_human $i
set i ''; set -gx i_mdi_human_child $i
set i ''; set -gx i_mdi_human_male_female $i
set i ''; set -gx i_mdi_image $i
set i ''; set -gx i_mdi_image_album $i
set i ''; set -gx i_mdi_image_area $i
set i ''; set -gx i_mdi_image_area_close $i
set i ''; set -gx i_mdi_image_broken $i
set i ''; set -gx i_mdi_image_broken_variant $i
set i ''; set -gx i_mdi_image_filter $i
set i ''; set -gx i_mdi_image_filter_black_white $i
set i ''; set -gx i_mdi_image_filter_center_focus $i
set i ''; set -gx i_mdi_image_filter_center_focus_weak $i
set i ''; set -gx i_mdi_image_filter_drama $i
set i ''; set -gx i_mdi_image_filter_frames $i
set i ''; set -gx i_mdi_image_filter_hdr $i
set i ''; set -gx i_mdi_image_filter_none $i
set i ''; set -gx i_mdi_image_filter_tilt_shift $i
set i ''; set -gx i_mdi_image_filter_vintage $i
set i ''; set -gx i_mdi_image_multiple $i
set i ''; set -gx i_mdi_import $i
set i ''; set -gx i_mdi_inbox_arrow_down $i
set i ''; set -gx i_mdi_information $i
set i ''; set -gx i_mdi_information_outline $i
set i ''; set -gx i_mdi_instagram $i
set i ''; set -gx i_mdi_instapaper $i
set i ''; set -gx i_mdi_internet_explorer $i
set i ''; set -gx i_mdi_invert_colors $i
set i ''; set -gx i_mdi_jeepney $i
set i ''; set -gx i_mdi_jira $i
set i ''; set -gx i_mdi_jsfiddle $i
set i ''; set -gx i_mdi_keg $i
set i ''; set -gx i_mdi_key $i
set i ''; set -gx i_mdi_key_change $i
set i ''; set -gx i_mdi_key_minus $i
set i ''; set -gx i_mdi_key_plus $i
set i ''; set -gx i_mdi_key_remove $i
set i ''; set -gx i_mdi_key_variant $i
set i ''; set -gx i_mdi_keyboard $i
set i ''; set -gx i_mdi_keyboard_backspace $i
set i ''; set -gx i_mdi_keyboard_caps $i
set i ''; set -gx i_mdi_keyboard_close $i
set i ''; set -gx i_mdi_keyboard_off $i
set i ''; set -gx i_mdi_keyboard_return $i
set i ''; set -gx i_mdi_keyboard_tab $i
set i ''; set -gx i_mdi_keyboard_variant $i
set i ''; set -gx i_mdi_kodi $i
set i ''; set -gx i_mdi_label $i
set i ''; set -gx i_mdi_label_outline $i
set i ''; set -gx i_mdi_lan $i
set i ''; set -gx i_mdi_lan_connect $i
set i ''; set -gx i_mdi_lan_disconnect $i
set i ''; set -gx i_mdi_lan_pending $i
set i ''; set -gx i_mdi_language_csharp $i
set i ''; set -gx i_mdi_language_css3 $i
set i ''; set -gx i_mdi_language_html5 $i
set i ''; set -gx i_mdi_language_javascript $i
set i ''; set -gx i_mdi_language_php $i
set i ''; set -gx i_mdi_language_python $i
set i ''; set -gx i_mdi_language_python_text $i
set i ''; set -gx i_mdi_laptop $i
set i ''; set -gx i_mdi_laptop_chromebook $i
set i ''; set -gx i_mdi_laptop_mac $i
set i ''; set -gx i_mdi_laptop_windows $i
set i ''; set -gx i_mdi_lastfm $i
set i ''; set -gx i_mdi_launch $i
set i ''; set -gx i_mdi_layers $i
set i ''; set -gx i_mdi_layers_off $i
set i ''; set -gx i_mdi_leaf $i
set i ''; set -gx i_mdi_led_off $i
set i ''; set -gx i_mdi_led_on $i
set i ''; set -gx i_mdi_led_outline $i
set i ''; set -gx i_mdi_led_variant_off $i
set i ''; set -gx i_mdi_led_variant_on $i
set i ''; set -gx i_mdi_led_variant_outline $i
set i ''; set -gx i_mdi_library $i
set i ''; set -gx i_mdi_library_books $i
set i ''; set -gx i_mdi_library_music $i
set i ''; set -gx i_mdi_library_plus $i
set i ''; set -gx i_mdi_lightbulb $i
set i ''; set -gx i_mdi_lightbulb_outline $i
set i ''; set -gx i_mdi_link $i
set i ''; set -gx i_mdi_link_off $i
set i ''; set -gx i_mdi_link_variant $i
set i ''; set -gx i_mdi_link_variant_off $i
set i ''; set -gx i_mdi_linkedin $i
set i ''; set -gx i_mdi_linkedin_box $i
set i ''; set -gx i_mdi_linux $i
set i ''; set -gx i_mdi_lock $i
set i ''; set -gx i_mdi_lock_open $i
set i ''; set -gx i_mdi_lock_open_outline $i
set i ''; set -gx i_mdi_lock_outline $i
set i ''; set -gx i_mdi_login $i
set i ''; set -gx i_mdi_logout $i
set i ''; set -gx i_mdi_looks $i
set i ''; set -gx i_mdi_loupe $i
set i ''; set -gx i_mdi_lumx $i
set i ''; set -gx i_mdi_magnet $i
set i ''; set -gx i_mdi_magnet_on $i
set i ''; set -gx i_mdi_magnify $i
set i ''; set -gx i_mdi_magnify_minus $i
set i ''; set -gx i_mdi_magnify_plus $i
set i ''; set -gx i_mdi_mail_ru $i
set i ''; set -gx i_mdi_map $i
set i ''; set -gx i_mdi_map_marker $i
set i ''; set -gx i_mdi_map_marker_circle $i
set i ''; set -gx i_mdi_map_marker_multiple $i
set i ''; set -gx i_mdi_map_marker_off $i
set i ''; set -gx i_mdi_map_marker_radius $i
set i ''; set -gx i_mdi_margin $i
set i ''; set -gx i_mdi_markdown $i
set i ''; set -gx i_mdi_marker_check $i
set i ''; set -gx i_mdi_martini $i
set i ''; set -gx i_mdi_material_ui $i
set i ''; set -gx i_mdi_math_compass $i
set i ''; set -gx i_mdi_maxcdn $i
set i ''; set -gx i_mdi_medium $i
set i ''; set -gx i_mdi_memory $i
set i ''; set -gx i_mdi_menu $i
set i ''; set -gx i_mdi_menu_down $i
set i ''; set -gx i_mdi_menu_left $i
set i ''; set -gx i_mdi_menu_right $i
set i ''; set -gx i_mdi_menu_up $i
set i ''; set -gx i_mdi_message $i
set i ''; set -gx i_mdi_message_alert $i
set i ''; set -gx i_mdi_message_draw $i
set i ''; set -gx i_mdi_message_image $i
set i ''; set -gx i_mdi_message_outline $i
set i ''; set -gx i_mdi_message_processing $i
set i ''; set -gx i_mdi_message_reply $i
set i ''; set -gx i_mdi_message_reply_text $i
set i ''; set -gx i_mdi_message_text $i
set i ''; set -gx i_mdi_message_text_outline $i
set i ''; set -gx i_mdi_message_video $i
set i ''; set -gx i_mdi_microphone $i
set i ''; set -gx i_mdi_microphone_off $i
set i ''; set -gx i_mdi_microphone_outline $i
set i ''; set -gx i_mdi_microphone_settings $i
set i ''; set -gx i_mdi_microphone_variant $i
set i ''; set -gx i_mdi_microphone_variant_off $i
set i ''; set -gx i_mdi_microsoft $i
set i ''; set -gx i_mdi_minecraft $i
set i ''; set -gx i_mdi_minus $i
set i ''; set -gx i_mdi_minus_box $i
set i ''; set -gx i_mdi_minus_circle $i
set i ''; set -gx i_mdi_minus_circle_outline $i
set i ''; set -gx i_mdi_minus_network $i
set i ''; set -gx i_mdi_monitor $i
set i ''; set -gx i_mdi_monitor_multiple $i
set i ''; set -gx i_mdi_more $i
set i ''; set -gx i_mdi_motorbike $i
set i ''; set -gx i_mdi_mouse $i
set i ''; set -gx i_mdi_mouse_off $i
set i ''; set -gx i_mdi_mouse_variant $i
set i ''; set -gx i_mdi_mouse_variant_off $i
set i ''; set -gx i_mdi_movie $i
set i ''; set -gx i_mdi_multiplication $i
set i ''; set -gx i_mdi_multiplication_box $i
set i ''; set -gx i_mdi_music_box $i
set i ''; set -gx i_mdi_music_box_outline $i
set i ''; set -gx i_mdi_music_circle $i
set i ''; set -gx i_mdi_music_note $i
set i ''; set -gx i_mdi_music_note_eighth $i
set i ''; set -gx i_mdi_music_note_half $i
set i ''; set -gx i_mdi_music_note_off $i
set i ''; set -gx i_mdi_music_note_quarter $i
set i ''; set -gx i_mdi_music_note_sixteenth $i
set i ''; set -gx i_mdi_music_note_whole $i
set i ''; set -gx i_mdi_nature $i
set i ''; set -gx i_mdi_nature_people $i
set i ''; set -gx i_mdi_navigation $i
set i ''; set -gx i_mdi_needle $i
set i ''; set -gx i_mdi_nest_protect $i
set i ''; set -gx i_mdi_nest_thermostat $i
set i ''; set -gx i_mdi_new_box $i
set i ''; set -gx i_mdi_newspaper $i
set i ''; set -gx i_mdi_nfc $i
set i ''; set -gx i_mdi_nfc_tap $i
set i ''; set -gx i_mdi_nfc_variant $i
set i ''; set -gx i_mdi_nodejs $i
set i ''; set -gx i_mdi_note $i
set i ''; set -gx i_mdi_note_outline $i
set i ''; set -gx i_mdi_note_plus $i
set i ''; set -gx i_mdi_note_plus_outline $i
set i ''; set -gx i_mdi_note_text $i
set i ''; set -gx i_mdi_notification_clear_all $i
set i ''; set -gx i_mdi_numeric $i
set i ''; set -gx i_mdi_numeric_0_box $i
set i ''; set -gx i_mdi_numeric_0_box_multiple_outline $i
set i ''; set -gx i_mdi_numeric_0_box_outline $i
set i ''; set -gx i_mdi_numeric_1_box $i
set i ''; set -gx i_mdi_numeric_1_box_multiple_outline $i
set i ''; set -gx i_mdi_numeric_1_box_outline $i
set i ''; set -gx i_mdi_numeric_2_box $i
set i ''; set -gx i_mdi_numeric_2_box_multiple_outline $i
set i ''; set -gx i_mdi_numeric_2_box_outline $i
set i ''; set -gx i_mdi_numeric_3_box $i
set i ''; set -gx i_mdi_numeric_3_box_multiple_outline $i
set i ''; set -gx i_mdi_numeric_3_box_outline $i
set i ''; set -gx i_mdi_numeric_4_box $i
set i ''; set -gx i_mdi_numeric_4_box_multiple_outline $i
set i ''; set -gx i_mdi_numeric_4_box_outline $i
set i ''; set -gx i_mdi_numeric_5_box $i
set i ''; set -gx i_mdi_numeric_5_box_multiple_outline $i
set i ''; set -gx i_mdi_numeric_5_box_outline $i
set i ''; set -gx i_mdi_numeric_6_box $i
set i ''; set -gx i_mdi_numeric_6_box_multiple_outline $i
set i ''; set -gx i_mdi_numeric_6_box_outline $i
set i ''; set -gx i_mdi_numeric_7_box $i
set i ''; set -gx i_mdi_numeric_7_box_multiple_outline $i
set i ''; set -gx i_mdi_numeric_7_box_outline $i
set i ''; set -gx i_mdi_numeric_8_box $i
set i ''; set -gx i_mdi_numeric_8_box_multiple_outline $i
set i ''; set -gx i_mdi_numeric_8_box_outline $i
set i ''; set -gx i_mdi_numeric_9_box $i
set i ''; set -gx i_mdi_numeric_9_box_multiple_outline $i
set i ''; set -gx i_mdi_numeric_9_box_outline $i
set i ''; set -gx i_mdi_numeric_9_plus_box $i
set i ''; set -gx i_mdi_numeric_9_plus_box_multiple_outline $i
set i ''; set -gx i_mdi_numeric_9_plus_box_outline $i
set i ''; set -gx i_mdi_nutrition $i
set i ''; set -gx i_mdi_octagon $i
set i ''; set -gx i_mdi_octagon_outline $i
set i ''; set -gx i_mdi_odnoklassniki $i
set i ''; set -gx i_mdi_office $i
set i ''; set -gx i_mdi_oil $i
set i ''; set -gx i_mdi_oil_temperature $i
set i ''; set -gx i_mdi_omega $i
set i ''; set -gx i_mdi_onedrive $i
set i ''; set -gx i_mdi_open_in_app $i
set i ''; set -gx i_mdi_open_in_new $i
set i ''; set -gx i_mdi_openid $i
set i ''; set -gx i_mdi_opera $i
set i ''; set -gx i_mdi_ornament $i
set i ''; set -gx i_mdi_ornament_variant $i
set i ''; set -gx i_mdi_inbox_arrow_up $i
set i ''; set -gx i_mdi_owl $i
set i ''; set -gx i_mdi_package $i
set i ''; set -gx i_mdi_package_down $i
set i ''; set -gx i_mdi_package_up $i
set i ''; set -gx i_mdi_package_variant $i
set i ''; set -gx i_mdi_package_variant_closed $i
set i ''; set -gx i_mdi_palette $i
set i ''; set -gx i_mdi_palette_advanced $i
set i ''; set -gx i_mdi_panda $i
set i ''; set -gx i_mdi_pandora $i
set i ''; set -gx i_mdi_panorama $i
set i ''; set -gx i_mdi_panorama_fisheye $i
set i ''; set -gx i_mdi_panorama_horizontal $i
set i ''; set -gx i_mdi_panorama_vertical $i
set i ''; set -gx i_mdi_panorama_wide_angle $i
set i ''; set -gx i_mdi_paper_cut_vertical $i
set i ''; set -gx i_mdi_paperclip $i
set i ''; set -gx i_mdi_parking $i
set i ''; set -gx i_mdi_pause $i
set i ''; set -gx i_mdi_pause_circle $i
set i ''; set -gx i_mdi_pause_circle_outline $i
set i ''; set -gx i_mdi_pause_octagon $i
set i ''; set -gx i_mdi_pause_octagon_outline $i
set i ''; set -gx i_mdi_paw $i
set i ''; set -gx i_mdi_pen $i
set i ''; set -gx i_mdi_pencil $i
set i ''; set -gx i_mdi_pencil_box $i
set i ''; set -gx i_mdi_pencil_box_outline $i
set i ''; set -gx i_mdi_pencil_lock $i
set i ''; set -gx i_mdi_pencil_off $i
set i ''; set -gx i_mdi_percent $i
set i ''; set -gx i_mdi_pharmacy $i
set i ''; set -gx i_mdi_phone $i
set i ''; set -gx i_mdi_phone_bluetooth $i
set i ''; set -gx i_mdi_phone_forward $i
set i ''; set -gx i_mdi_phone_hangup $i
set i ''; set -gx i_mdi_phone_in_talk $i
set i ''; set -gx i_mdi_phone_incoming $i
set i ''; set -gx i_mdi_phone_locked $i
set i ''; set -gx i_mdi_phone_log $i
set i ''; set -gx i_mdi_phone_missed $i
set i ''; set -gx i_mdi_phone_outgoing $i
set i ''; set -gx i_mdi_phone_paused $i
set i ''; set -gx i_mdi_phone_settings $i
set i ''; set -gx i_mdi_phone_voip $i
set i ''; set -gx i_mdi_pi $i
set i ''; set -gx i_mdi_pi_box $i
set i '豈'; set -gx i_mdi_pig $i
set i '更'; set -gx i_mdi_pill $i
set i '車'; set -gx i_mdi_pin $i
set i '賈'; set -gx i_mdi_pin_off $i
set i '滑'; set -gx i_mdi_pine_tree $i
set i '串'; set -gx i_mdi_pine_tree_box $i
set i '句'; set -gx i_mdi_pinterest $i
set i '龜'; set -gx i_mdi_pinterest_box $i
set i '龜'; set -gx i_mdi_pizza $i
set i '契'; set -gx i_mdi_play $i
set i '金'; set -gx i_mdi_play_box_outline $i
set i '喇'; set -gx i_mdi_play_circle $i
set i '奈'; set -gx i_mdi_play_circle_outline $i
set i '懶'; set -gx i_mdi_play_pause $i
set i '癩'; set -gx i_mdi_play_protected_content $i
set i '羅'; set -gx i_mdi_playlist_minus $i
set i '蘿'; set -gx i_mdi_playlist_play $i
set i '螺'; set -gx i_mdi_playlist_plus $i
set i '裸'; set -gx i_mdi_playlist_remove $i
set i '邏'; set -gx i_mdi_playstation $i
set i '樂'; set -gx i_mdi_plus $i
set i '洛'; set -gx i_mdi_plus_box $i
set i '烙'; set -gx i_mdi_plus_circle $i
set i '珞'; set -gx i_mdi_plus_circle_multiple_outline $i
set i '落'; set -gx i_mdi_plus_circle_outline $i
set i '酪'; set -gx i_mdi_plus_network $i
set i '駱'; set -gx i_mdi_plus_one $i
set i '亂'; set -gx i_mdi_pocket $i
set i '卵'; set -gx i_mdi_pokeball $i
set i '欄'; set -gx i_mdi_polaroid $i
set i '爛'; set -gx i_mdi_poll $i
set i '蘭'; set -gx i_mdi_poll_box $i
set i '鸞'; set -gx i_mdi_polymer $i
set i '嵐'; set -gx i_mdi_popcorn $i
set i '濫'; set -gx i_mdi_pound $i
set i '藍'; set -gx i_mdi_pound_box $i
set i '襤'; set -gx i_mdi_power $i
set i '拉'; set -gx i_mdi_power_settings $i
set i '臘'; set -gx i_mdi_power_socket $i
set i '蠟'; set -gx i_mdi_presentation $i
set i '廊'; set -gx i_mdi_presentation_play $i
set i '朗'; set -gx i_mdi_printer $i
set i '浪'; set -gx i_mdi_printer_3d $i
set i '狼'; set -gx i_mdi_printer_alert $i
set i '郎'; set -gx i_mdi_professional_hexagon $i
set i '來'; set -gx i_mdi_projector $i
set i '冷'; set -gx i_mdi_projector_screen $i
set i '勞'; set -gx i_mdi_pulse $i
set i '擄'; set -gx i_mdi_puzzle $i
set i '櫓'; set -gx i_mdi_qrcode $i
set i '爐'; set -gx i_mdi_qrcode_scan $i
set i '盧'; set -gx i_mdi_quadcopter $i
set i '老'; set -gx i_mdi_quality_high $i
set i '蘆'; set -gx i_mdi_quicktime $i
set i '虜'; set -gx i_mdi_radar $i
set i '路'; set -gx i_mdi_radiator $i
set i '露'; set -gx i_mdi_radio $i
set i '魯'; set -gx i_mdi_radio_handheld $i
set i '鷺'; set -gx i_mdi_radio_tower $i
set i '碌'; set -gx i_mdi_radioactive $i
set i '祿'; set -gx i_mdi_radiobox_blank $i
set i '綠'; set -gx i_mdi_radiobox_marked $i
set i '菉'; set -gx i_mdi_raspberrypi $i
set i '錄'; set -gx i_mdi_ray_end $i
set i '鹿'; set -gx i_mdi_ray_end_arrow $i
set i '論'; set -gx i_mdi_ray_start $i
set i '壟'; set -gx i_mdi_ray_start_arrow $i
set i '弄'; set -gx i_mdi_ray_start_end $i
set i '籠'; set -gx i_mdi_ray_vertex $i
set i '聾'; set -gx i_mdi_lastpass $i
set i '牢'; set -gx i_mdi_read $i
set i '磊'; set -gx i_mdi_youtube_tv $i
set i '賂'; set -gx i_mdi_receipt $i
set i '雷'; set -gx i_mdi_record $i
set i '壘'; set -gx i_mdi_record_rec $i
set i '屢'; set -gx i_mdi_recycle $i
set i '樓'; set -gx i_mdi_reddit $i
set i '淚'; set -gx i_mdi_redo $i
set i '漏'; set -gx i_mdi_redo_variant $i
set i '累'; set -gx i_mdi_refresh $i
set i '縷'; set -gx i_mdi_regex $i
set i '陋'; set -gx i_mdi_relative_scale $i
set i '勒'; set -gx i_mdi_reload $i
set i '肋'; set -gx i_mdi_remote $i
set i '凜'; set -gx i_mdi_rename_box $i
set i '凌'; set -gx i_mdi_repeat $i
set i '稜'; set -gx i_mdi_repeat_off $i
set i '綾'; set -gx i_mdi_repeat_once $i
set i '菱'; set -gx i_mdi_replay $i
set i '陵'; set -gx i_mdi_reply $i
set i '讀'; set -gx i_mdi_reply_all $i
set i '拏'; set -gx i_mdi_reproduction $i
set i '樂'; set -gx i_mdi_resize_bottom_right $i
set i '諾'; set -gx i_mdi_responsive $i
set i '丹'; set -gx i_mdi_rewind $i
set i '寧'; set -gx i_mdi_ribbon $i
set i '怒'; set -gx i_mdi_road $i
set i '率'; set -gx i_mdi_road_variant $i
set i '異'; set -gx i_mdi_rocket $i
set i '北'; set -gx i_mdi_rotate_3d $i
set i '磻'; set -gx i_mdi_rotate_left $i
set i '便'; set -gx i_mdi_rotate_left_variant $i
set i '復'; set -gx i_mdi_rotate_right $i
set i '不'; set -gx i_mdi_rotate_right_variant $i
set i '泌'; set -gx i_mdi_router_wireless $i
set i '數'; set -gx i_mdi_routes $i
set i '索'; set -gx i_mdi_rss $i
set i '參'; set -gx i_mdi_rss_box $i
set i '塞'; set -gx i_mdi_ruler $i
set i '省'; set -gx i_mdi_run_fast $i
set i '葉'; set -gx i_mdi_sale $i
set i '說'; set -gx i_mdi_satellite $i
set i '殺'; set -gx i_mdi_satellite_variant $i
set i '辰'; set -gx i_mdi_scale $i
set i '沈'; set -gx i_mdi_scale_bathroom $i
set i '拾'; set -gx i_mdi_school $i
set i '若'; set -gx i_mdi_screen_rotation $i
set i '掠'; set -gx i_mdi_screen_rotation_lock $i
set i '略'; set -gx i_mdi_screwdriver $i
set i '亮'; set -gx i_mdi_script $i
set i '兩'; set -gx i_mdi_sd $i
set i '凉'; set -gx i_mdi_seal $i
set i '梁'; set -gx i_mdi_seat_flat $i
set i '糧'; set -gx i_mdi_seat_flat_angled $i
set i '良'; set -gx i_mdi_seat_individual_suite $i
set i '諒'; set -gx i_mdi_seat_legroom_extra $i
set i '量'; set -gx i_mdi_seat_legroom_normal $i
set i '勵'; set -gx i_mdi_seat_legroom_reduced $i
set i '呂'; set -gx i_mdi_seat_recline_extra $i
set i '女'; set -gx i_mdi_seat_recline_normal $i
set i '廬'; set -gx i_mdi_security $i
set i '旅'; set -gx i_mdi_security_network $i
set i '濾'; set -gx i_mdi_select $i
set i '礪'; set -gx i_mdi_select_all $i
set i '閭'; set -gx i_mdi_select_inverse $i
set i '驪'; set -gx i_mdi_select_off $i
set i '麗'; set -gx i_mdi_selection $i
set i '黎'; set -gx i_mdi_send $i
set i '力'; set -gx i_mdi_server $i
set i '曆'; set -gx i_mdi_server_minus $i
set i '歷'; set -gx i_mdi_server_network $i
set i '轢'; set -gx i_mdi_server_network_off $i
set i '年'; set -gx i_mdi_server_off $i
set i '憐'; set -gx i_mdi_server_plus $i
set i '戀'; set -gx i_mdi_server_remove $i
set i '撚'; set -gx i_mdi_server_security $i
set i '漣'; set -gx i_mdi_settings $i
set i '煉'; set -gx i_mdi_settings_box $i
set i '璉'; set -gx i_mdi_shape_plus $i
set i '秊'; set -gx i_mdi_share $i
set i '練'; set -gx i_mdi_share_variant $i
set i '聯'; set -gx i_mdi_shield $i
set i '輦'; set -gx i_mdi_shield_outline $i
set i '蓮'; set -gx i_mdi_shopping $i
set i '連'; set -gx i_mdi_shopping_music $i
set i '鍊'; set -gx i_mdi_shredder $i
set i '列'; set -gx i_mdi_shuffle $i
set i '劣'; set -gx i_mdi_shuffle_disabled $i
set i '咽'; set -gx i_mdi_shuffle_variant $i
set i '烈'; set -gx i_mdi_sigma $i
set i '裂'; set -gx i_mdi_sign_caution $i
set i '說'; set -gx i_mdi_signal $i
set i '廉'; set -gx i_mdi_silverware $i
set i '念'; set -gx i_mdi_silverware_fork $i
set i '捻'; set -gx i_mdi_silverware_spoon $i
set i '殮'; set -gx i_mdi_silverware_variant $i
set i '簾'; set -gx i_mdi_sim $i
set i '獵'; set -gx i_mdi_sim_alert $i
set i '令'; set -gx i_mdi_sim_off $i
set i '囹'; set -gx i_mdi_sitemap $i
set i '寧'; set -gx i_mdi_skip_backward $i
set i '嶺'; set -gx i_mdi_skip_forward $i
set i '怜'; set -gx i_mdi_skip_next $i
set i '玲'; set -gx i_mdi_skip_previous $i
set i '瑩'; set -gx i_mdi_skype $i
set i '羚'; set -gx i_mdi_skype_business $i
set i '聆'; set -gx i_mdi_slack $i
set i '鈴'; set -gx i_mdi_sleep $i
set i '零'; set -gx i_mdi_sleep_off $i
set i '靈'; set -gx i_mdi_smoking $i
set i '領'; set -gx i_mdi_smoking_off $i
set i '例'; set -gx i_mdi_snapchat $i
set i '禮'; set -gx i_mdi_snowman $i
set i '醴'; set -gx i_mdi_soccer $i
set i '隸'; set -gx i_mdi_sofa $i
set i '惡'; set -gx i_mdi_sort $i
set i '了'; set -gx i_mdi_sort_alphabetical $i
set i '僚'; set -gx i_mdi_sort_ascending $i
set i '寮'; set -gx i_mdi_sort_descending $i
set i '尿'; set -gx i_mdi_sort_numeric $i
set i '料'; set -gx i_mdi_sort_variant $i
set i '樂'; set -gx i_mdi_soundcloud $i
set i '燎'; set -gx i_mdi_source_fork $i
set i '療'; set -gx i_mdi_source_pull $i
set i '蓼'; set -gx i_mdi_speaker $i
set i '遼'; set -gx i_mdi_speaker_off $i
set i '龍'; set -gx i_mdi_speedometer $i
set i '暈'; set -gx i_mdi_spellcheck $i
set i '阮'; set -gx i_mdi_spotify $i
set i '劉'; set -gx i_mdi_spotlight $i
set i '杻'; set -gx i_mdi_spotlight_beam $i
set i '柳'; set -gx i_mdi_square_inc $i
set i '流'; set -gx i_mdi_square_inc_cash $i
set i '溜'; set -gx i_mdi_stack_overflow $i
set i '琉'; set -gx i_mdi_stairs $i
set i '留'; set -gx i_mdi_star $i
set i '硫'; set -gx i_mdi_star_circle $i
set i '紐'; set -gx i_mdi_star_half $i
set i '類'; set -gx i_mdi_star_off $i
set i '六'; set -gx i_mdi_star_outline $i
set i '戮'; set -gx i_mdi_steam $i
set i '陸'; set -gx i_mdi_steering $i
set i '倫'; set -gx i_mdi_step_backward $i
set i '崙'; set -gx i_mdi_step_backward_2 $i
set i '淪'; set -gx i_mdi_step_forward $i
set i '輪'; set -gx i_mdi_step_forward_2 $i
set i '律'; set -gx i_mdi_stethoscope $i
set i '慄'; set -gx i_mdi_stocking $i
set i '栗'; set -gx i_mdi_stop $i
set i '率'; set -gx i_mdi_store $i
set i '隆'; set -gx i_mdi_store_24_hour $i
set i '利'; set -gx i_mdi_stove $i
set i '吏'; set -gx i_mdi_subway_variant $i
set i '履'; set -gx i_mdi_sunglasses $i
set i '易'; set -gx i_mdi_swap_horizontal $i
set i '李'; set -gx i_mdi_swap_vertical $i
set i '梨'; set -gx i_mdi_swim $i
set i '泥'; set -gx i_mdi_switch $i
set i '理'; set -gx i_mdi_sword $i
set i '痢'; set -gx i_mdi_sync $i
set i '罹'; set -gx i_mdi_sync_alert $i
set i '裏'; set -gx i_mdi_sync_off $i
set i '裡'; set -gx i_mdi_tab $i
set i '里'; set -gx i_mdi_tab_unselected $i
set i '離'; set -gx i_mdi_table $i
set i '匿'; set -gx i_mdi_table_column_plus_after $i
set i '溺'; set -gx i_mdi_table_column_plus_before $i
set i '吝'; set -gx i_mdi_table_column_remove $i
set i '燐'; set -gx i_mdi_table_column_width $i
set i '璘'; set -gx i_mdi_table_edit $i
set i '藺'; set -gx i_mdi_table_large $i
set i '隣'; set -gx i_mdi_table_row_height $i
set i '鱗'; set -gx i_mdi_table_row_plus_after $i
set i '麟'; set -gx i_mdi_table_row_plus_before $i
set i '林'; set -gx i_mdi_table_row_remove $i
set i '淋'; set -gx i_mdi_tablet $i
set i '臨'; set -gx i_mdi_tablet_android $i
set i '立'; set -gx i_mdi_tablet_ipad $i
set i '笠'; set -gx i_mdi_tag $i
set i '粒'; set -gx i_mdi_tag_faces $i
set i '狀'; set -gx i_mdi_tag_multiple $i
set i '炙'; set -gx i_mdi_tag_outline $i
set i '識'; set -gx i_mdi_tag_text_outline $i
set i '什'; set -gx i_mdi_target $i
set i '茶'; set -gx i_mdi_taxi $i
set i '刺'; set -gx i_mdi_teamviewer $i
set i '切'; set -gx i_mdi_telegram $i
set i '度'; set -gx i_mdi_television $i
set i '拓'; set -gx i_mdi_television_guide $i
set i '糖'; set -gx i_mdi_temperature_celsius $i
set i '宅'; set -gx i_mdi_temperature_fahrenheit $i
set i '洞'; set -gx i_mdi_temperature_kelvin $i
set i '暴'; set -gx i_mdi_tennis $i
set i '輻'; set -gx i_mdi_tent $i
set i '行'; set -gx i_mdi_terrain $i
set i '降'; set -gx i_mdi_text_to_speech $i
set i '見'; set -gx i_mdi_text_to_speech_off $i
set i '廓'; set -gx i_mdi_texture $i
set i '兀'; set -gx i_mdi_theater $i
set i '嗀'; set -gx i_mdi_theme_light_dark $i
set i '﨎'; set -gx i_mdi_thermometer $i
set i '﨏'; set -gx i_mdi_thermometer_lines $i
set i '塚'; set -gx i_mdi_thumb_down $i
set i '﨑'; set -gx i_mdi_thumb_down_outline $i
set i '晴'; set -gx i_mdi_thumb_up $i
set i '﨓'; set -gx i_mdi_thumb_up_outline $i
set i '﨔'; set -gx i_mdi_thumbs_up_down $i
set i '凞'; set -gx i_mdi_ticket $i
set i '猪'; set -gx i_mdi_ticket_account $i
set i '益'; set -gx i_mdi_ticket_confirmation $i
set i '礼'; set -gx i_mdi_tie $i
set i '神'; set -gx i_mdi_timelapse $i
set i '祥'; set -gx i_mdi_timer $i
set i '福'; set -gx i_mdi_timer_10 $i
set i '靖'; set -gx i_mdi_timer_3 $i
set i '精'; set -gx i_mdi_timer_off $i
set i '羽'; set -gx i_mdi_timer_sand $i
set i '﨟'; set -gx i_mdi_timetable $i
set i '蘒'; set -gx i_mdi_toggle_switch $i
set i '﨡'; set -gx i_mdi_toggle_switch_off $i
set i '諸'; set -gx i_mdi_tooltip $i
set i '﨣'; set -gx i_mdi_tooltip_edit $i
set i '﨤'; set -gx i_mdi_tooltip_image $i
set i '逸'; set -gx i_mdi_tooltip_outline $i
set i '都'; set -gx i_mdi_tooltip_outline_plus $i
set i '﨧'; set -gx i_mdi_tooltip_text $i
set i '﨨'; set -gx i_mdi_tooth $i
set i '﨩'; set -gx i_mdi_tor $i
set i '飯'; set -gx i_mdi_traffic_light $i
set i '飼'; set -gx i_mdi_train $i
set i '館'; set -gx i_mdi_tram $i
set i '鶴'; set -gx i_mdi_transcribe $i
set i '郞'; set -gx i_mdi_transcribe_close $i
set i '隷'; set -gx i_mdi_transfer $i
set i '侮'; set -gx i_mdi_tree $i
set i '僧'; set -gx i_mdi_trello $i
set i '免'; set -gx i_mdi_trending_down $i
set i '勉'; set -gx i_mdi_trending_neutral $i
set i '勤'; set -gx i_mdi_trending_up $i
set i '卑'; set -gx i_mdi_triangle $i
set i '喝'; set -gx i_mdi_triangle_outline $i
set i '嘆'; set -gx i_mdi_trophy $i
set i '器'; set -gx i_mdi_trophy_award $i
set i '塀'; set -gx i_mdi_trophy_outline $i
set i '墨'; set -gx i_mdi_trophy_variant $i
set i '層'; set -gx i_mdi_trophy_variant_outline $i
set i '屮'; set -gx i_mdi_truck $i
set i '悔'; set -gx i_mdi_truck_delivery $i
set i '慨'; set -gx i_mdi_tshirt_crew $i
set i '憎'; set -gx i_mdi_tshirt_v $i
set i '懲'; set -gx i_mdi_tumblr $i
set i '敏'; set -gx i_mdi_tumblr_reblog $i
set i '既'; set -gx i_mdi_twitch $i
set i '暑'; set -gx i_mdi_twitter $i
set i '梅'; set -gx i_mdi_twitter_box $i
set i '海'; set -gx i_mdi_twitter_circle $i
set i '渚'; set -gx i_mdi_twitter_retweet $i
set i '漢'; set -gx i_mdi_ubuntu $i
set i '煮'; set -gx i_mdi_umbraco $i
set i '爫'; set -gx i_mdi_umbrella $i
set i '琢'; set -gx i_mdi_umbrella_outline $i
set i '碑'; set -gx i_mdi_undo $i
set i '社'; set -gx i_mdi_undo_variant $i
set i '祉'; set -gx i_mdi_unfold_less_horizontal $i
set i '祈'; set -gx i_mdi_unfold_more_horizontal $i
set i '祐'; set -gx i_mdi_ungroup $i
set i '祖'; set -gx i_mdi_untappd $i
set i '祝'; set -gx i_mdi_upload $i
set i '禍'; set -gx i_mdi_usb $i
set i '禎'; set -gx i_mdi_vector_arrange_above $i
set i '穀'; set -gx i_mdi_vector_arrange_below $i
set i '突'; set -gx i_mdi_vector_circle $i
set i '節'; set -gx i_mdi_vector_circle_variant $i
set i '練'; set -gx i_mdi_vector_combine $i
set i '縉'; set -gx i_mdi_vector_curve $i
set i '繁'; set -gx i_mdi_vector_difference $i
set i '署'; set -gx i_mdi_vector_difference_ab $i
set i '者'; set -gx i_mdi_vector_difference_ba $i
set i '臭'; set -gx i_mdi_vector_intersection $i
set i '艹'; set -gx i_mdi_vector_line $i
set i '艹'; set -gx i_mdi_vector_point $i
set i '著'; set -gx i_mdi_vector_polygon $i
set i '褐'; set -gx i_mdi_vector_polyline $i
set i '視'; set -gx i_mdi_vector_selection $i
set i '謁'; set -gx i_mdi_vector_triangle $i
set i '謹'; set -gx i_mdi_vector_union $i
set i '賓'; set -gx i_mdi_verified $i
set i '贈'; set -gx i_mdi_vibrate $i
set i '辶'; set -gx i_mdi_video $i
set i '逸'; set -gx i_mdi_video_off $i
set i '難'; set -gx i_mdi_video_switch $i
set i '響'; set -gx i_mdi_view_agenda $i
set i '頻'; set -gx i_mdi_view_array $i
set i '恵'; set -gx i_mdi_view_carousel $i
set i '𤋮'; set -gx i_mdi_view_column $i
set i '舘'; set -gx i_mdi_view_dashboard $i
set i '﩮'; set -gx i_mdi_view_day $i
set i '﩯'; set -gx i_mdi_view_grid $i
set i '並'; set -gx i_mdi_view_headline $i
set i '况'; set -gx i_mdi_view_list $i
set i '全'; set -gx i_mdi_view_module $i
set i '侀'; set -gx i_mdi_view_quilt $i
set i '充'; set -gx i_mdi_view_stream $i
set i '冀'; set -gx i_mdi_view_week $i
set i '勇'; set -gx i_mdi_vimeo $i
set i '勺'; set -gx i_mdi_venmo $i
set i '喝'; set -gx i_mdi_vk $i
set i '啕'; set -gx i_mdi_vk_box $i
set i '喙'; set -gx i_mdi_vk_circle $i
set i '嗢'; set -gx i_mdi_vlc $i
set i '塚'; set -gx i_mdi_voicemail $i
set i '墳'; set -gx i_mdi_volume_high $i
set i '奄'; set -gx i_mdi_volume_low $i
set i '奔'; set -gx i_mdi_volume_medium $i
set i '婢'; set -gx i_mdi_volume_off $i
set i '嬨'; set -gx i_mdi_vpn $i
set i '廒'; set -gx i_mdi_walk $i
set i '廙'; set -gx i_mdi_wallet $i
set i '彩'; set -gx i_mdi_wallet_giftcard $i
set i '徭'; set -gx i_mdi_wallet_membership $i
set i '惘'; set -gx i_mdi_wallet_travel $i
set i '慎'; set -gx i_mdi_wan $i
set i '愈'; set -gx i_mdi_watch $i
set i '憎'; set -gx i_mdi_watch_export $i
set i '慠'; set -gx i_mdi_watch_import $i
set i '懲'; set -gx i_mdi_water $i
set i '戴'; set -gx i_mdi_water_off $i
set i '揄'; set -gx i_mdi_water_percent $i
set i '搜'; set -gx i_mdi_water_pump $i
set i '摒'; set -gx i_mdi_weather_cloudy $i
set i '敖'; set -gx i_mdi_weather_fog $i
set i '晴'; set -gx i_mdi_weather_hail $i
set i '朗'; set -gx i_mdi_weather_lightning $i
set i '望'; set -gx i_mdi_weather_night $i
set i '杖'; set -gx i_mdi_weather_partlycloudy $i
set i '歹'; set -gx i_mdi_weather_pouring $i
set i '殺'; set -gx i_mdi_weather_rainy $i
set i '流'; set -gx i_mdi_weather_snowy $i
set i '滛'; set -gx i_mdi_weather_sunny $i
set i '滋'; set -gx i_mdi_weather_sunset $i
set i '漢'; set -gx i_mdi_weather_sunset_down $i
set i '瀞'; set -gx i_mdi_weather_sunset_up $i
set i '煮'; set -gx i_mdi_weather_windy $i
set i '瞧'; set -gx i_mdi_weather_windy_variant $i
set i '爵'; set -gx i_mdi_web $i
set i '犯'; set -gx i_mdi_webcam $i
set i '猪'; set -gx i_mdi_weight $i
set i '瑱'; set -gx i_mdi_weight_kilogram $i
set i '甆'; set -gx i_mdi_whatsapp $i
set i '画'; set -gx i_mdi_wheelchair_accessibility $i
set i '瘝'; set -gx i_mdi_white_balance_auto $i
set i '瘟'; set -gx i_mdi_white_balance_incandescent $i
set i '益'; set -gx i_mdi_white_balance_iridescent $i
set i '盛'; set -gx i_mdi_white_balance_sunny $i
set i '直'; set -gx i_mdi_wifi $i
set i '睊'; set -gx i_mdi_wifi_off $i
set i '着'; set -gx i_mdi_wii $i
set i '磌'; set -gx i_mdi_wikipedia $i
set i '窱'; set -gx i_mdi_window_close $i
set i '節'; set -gx i_mdi_window_closed $i
set i '类'; set -gx i_mdi_window_maximize $i
set i '絛'; set -gx i_mdi_window_minimize $i
set i '練'; set -gx i_mdi_window_open $i
set i '缾'; set -gx i_mdi_window_restore $i
set i '者'; set -gx i_mdi_windows $i
set i '荒'; set -gx i_mdi_wordpress $i
set i '華'; set -gx i_mdi_worker $i
set i '蝹'; set -gx i_mdi_wrap $i
set i '襁'; set -gx i_mdi_wrench $i
set i '覆'; set -gx i_mdi_wunderlist $i
set i '視'; set -gx i_mdi_xbox $i
set i '調'; set -gx i_mdi_xbox_controller $i
set i '諸'; set -gx i_mdi_xbox_controller_off $i
set i '請'; set -gx i_mdi_xda $i
set i '謁'; set -gx i_mdi_xing $i
set i '諾'; set -gx i_mdi_xing_box $i
set i '諭'; set -gx i_mdi_xing_circle $i
set i '謹'; set -gx i_mdi_xml $i
set i '變'; set -gx i_mdi_yeast $i
set i '贈'; set -gx i_mdi_yelp $i
set i '輸'; set -gx i_mdi_youtube_play $i
set i '遲'; set -gx i_mdi_zip_box $i
set i '醙'; set -gx i_mdi_surround_sound $i
set i '鉶'; set -gx i_mdi_vector_rectangle $i
set i '陼'; set -gx i_mdi_playlist_check $i
set i '難'; set -gx i_mdi_format_line_style $i
set i '靖'; set -gx i_mdi_format_line_weight $i
set i '韛'; set -gx i_mdi_translate $i
set i '響'; set -gx i_mdi_voice $i
set i '頋'; set -gx i_mdi_opacity $i
set i '頻'; set -gx i_mdi_near_me $i
set i '鬒'; set -gx i_mdi_clock_alert $i
set i '龜'; set -gx i_mdi_human_pregnant $i
set i '𢡊'; set -gx i_mdi_sticker $i
set i '𢡄'; set -gx i_mdi_scale_balance $i
set i '𣏕'; set -gx i_mdi_account_card_details $i
set i '㮝'; set -gx i_mdi_account_multiple_minus $i
set i '䀘'; set -gx i_mdi_airplane_landing $i
set i '䀹'; set -gx i_mdi_airplane_takeoff $i
set i '𥉉'; set -gx i_mdi_alert_circle_outline $i
set i '𥳐'; set -gx i_mdi_altimeter $i
set i '𧻓'; set -gx i_mdi_animation $i
set i '齃'; set -gx i_mdi_book_minus $i
set i '龎'; set -gx i_mdi_book_open_page_variant $i
set i '﫚'; set -gx i_mdi_book_plus $i
set i '﫛'; set -gx i_mdi_boombox $i
set i '﫜'; set -gx i_mdi_bullseye $i
set i '﫝'; set -gx i_mdi_comment_remove $i
set i '﫞'; set -gx i_mdi_camera_off $i
set i '﫟'; set -gx i_mdi_check_circle $i
set i '﫠'; set -gx i_mdi_check_circle_outline $i
set i '﫡'; set -gx i_mdi_candle $i
set i '﫢'; set -gx i_mdi_chart_bubble $i
set i '﫣'; set -gx i_mdi_credit_card_off $i
set i '﫤'; set -gx i_mdi_cup_off $i
set i '﫥'; set -gx i_mdi_copyright $i
set i '﫦'; set -gx i_mdi_cursor_text $i
set i '﫧'; set -gx i_mdi_delete_forever $i
set i '﫨'; set -gx i_mdi_delete_sweep $i
set i '﫩'; set -gx i_mdi_dice_d20 $i
set i '﫪'; set -gx i_mdi_dice_d4 $i
set i '﫫'; set -gx i_mdi_dice_d6 $i
set i '﫬'; set -gx i_mdi_dice_d8 $i
set i '﫭'; set -gx i_mdi_disk $i
set i '﫮'; set -gx i_mdi_email_open_outline $i
set i '﫯'; set -gx i_mdi_email_variant $i
set i '﫰'; set -gx i_mdi_ev_station $i
set i '﫱'; set -gx i_mdi_food_fork_drink $i
set i '﫲'; set -gx i_mdi_food_off $i
set i '﫳'; set -gx i_mdi_format_title $i
set i '﫴'; set -gx i_mdi_google_maps $i
set i '﫵'; set -gx i_mdi_heart_pulse $i
set i '﫶'; set -gx i_mdi_highway $i
set i '﫷'; set -gx i_mdi_home_map_marker $i
set i '﫸'; set -gx i_mdi_incognito $i
set i '﫹'; set -gx i_mdi_kettle $i
set i '﫺'; set -gx i_mdi_lock_plus $i
set i '﫻'; set -gx i_mdi_login_variant $i
set i '﫼'; set -gx i_mdi_logout_variant $i
set i '﫽'; set -gx i_mdi_music_note_bluetooth $i
set i '﫾'; set -gx i_mdi_music_note_bluetooth_off $i
set i '﫿'; set -gx i_mdi_page_first $i
set i 'ﬀ'; set -gx i_mdi_page_last $i
set i 'ﬁ'; set -gx i_mdi_phone_classic $i
set i 'ﬂ'; set -gx i_mdi_priority_high $i
set i 'ﬃ'; set -gx i_mdi_priority_low $i
set i 'ﬄ'; set -gx i_mdi_qqchat $i
set i 'ﬅ'; set -gx i_mdi_pool $i
set i 'ﬆ'; set -gx i_mdi_rounded_corner $i
set i '﬇'; set -gx i_mdi_rowing $i
set i '﬈'; set -gx i_mdi_saxophone $i
set i '﬉'; set -gx i_mdi_signal_variant $i
set i '﬊'; set -gx i_mdi_stackexchange $i
set i '﬋'; set -gx i_mdi_subdirectory_arrow_left $i
set i '﬌'; set -gx i_mdi_subdirectory_arrow_right $i
set i '﬍'; set -gx i_mdi_textbox $i
set i '﬎'; set -gx i_mdi_violin $i
set i '﬏'; set -gx i_mdi_visualstudio $i
set i '﬐'; set -gx i_mdi_wechat $i
set i '﬑'; set -gx i_mdi_watermark $i
set i '﬒'; set -gx i_mdi_file_hidden $i
set i 'ﬓ'; set -gx i_mdi_application $i
set i 'ﬔ'; set -gx i_mdi_arrow_collapse $i
set i 'ﬕ'; set -gx i_mdi_arrow_expand $i
set i 'ﬖ'; set -gx i_mdi_bowl $i
set i 'ﬗ'; set -gx i_mdi_bridge $i
set i '﬘'; set -gx i_mdi_buffer $i
set i '﬙'; set -gx i_mdi_chip $i
set i '﬚'; set -gx i_mdi_content_save_settings $i
set i '﬛'; set -gx i_mdi_dialpad $i
set i '﬜'; set -gx i_mdi_dictionary $i
set i 'יִ'; set -gx i_mdi_format_horizontal_align_center $i
set i 'ﬞ'; set -gx i_mdi_format_horizontal_align_left $i
set i 'ײַ'; set -gx i_mdi_format_horizontal_align_right $i
set i 'ﬠ'; set -gx i_mdi_format_vertical_align_bottom $i
set i 'ﬡ'; set -gx i_mdi_format_vertical_align_center $i
set i 'ﬢ'; set -gx i_mdi_format_vertical_align_top $i
set i 'ﬣ'; set -gx i_mdi_hackernews $i
set i 'ﬤ'; set -gx i_mdi_help_circle_outline $i
set i 'ﬥ'; set -gx i_mdi_json $i
set i 'ﬦ'; set -gx i_mdi_lambda $i
set i 'ﬧ'; set -gx i_mdi_matrix $i
set i 'ﬨ'; set -gx i_mdi_meteor $i
set i '﬩'; set -gx i_mdi_mixcloud $i
set i 'שׁ'; set -gx i_mdi_sigma_lower $i
set i 'שׂ'; set -gx i_mdi_source_branch $i
set i 'שּׁ'; set -gx i_mdi_source_merge $i
set i 'שּׂ'; set -gx i_mdi_tune $i
set i 'אַ'; set -gx i_mdi_webhook $i
set i 'אָ'; set -gx i_mdi_account_settings $i
set i 'אּ'; set -gx i_mdi_account_settings_variant $i
set i 'בּ'; set -gx i_mdi_apple_keyboard_caps $i
set i 'גּ'; set -gx i_mdi_apple_keyboard_command $i
set i 'דּ'; set -gx i_mdi_apple_keyboard_control $i
set i 'הּ'; set -gx i_mdi_apple_keyboard_option $i
set i 'וּ'; set -gx i_mdi_apple_keyboard_shift $i
set i 'זּ'; set -gx i_mdi_box_shadow $i
set i '﬷'; set -gx i_mdi_cards $i
set i 'טּ'; set -gx i_mdi_cards_outline $i
set i 'יּ'; set -gx i_mdi_cards_playing_outline $i
set i 'ךּ'; set -gx i_mdi_checkbox_multiple_blank_circle $i
set i 'כּ'; set -gx i_mdi_checkbox_multiple_blank_circle_outline $i
set i 'לּ'; set -gx i_mdi_checkbox_multiple_marked_circle $i
set i '﬽'; set -gx i_mdi_checkbox_multiple_marked_circle_outline $i
set i 'מּ'; set -gx i_mdi_cloud_sync $i
set i '﬿'; set -gx i_mdi_collage $i
set i 'נּ'; set -gx i_mdi_directions_fork $i
set i 'סּ'; set -gx i_mdi_eraser_variant $i
set i '﭂'; set -gx i_mdi_face $i
set i 'ףּ'; set -gx i_mdi_face_profile $i
set i 'פּ'; set -gx i_mdi_file_tree $i
set i '﭅'; set -gx i_mdi_format_annotation_plus $i
set i 'צּ'; set -gx i_mdi_gas_cylinder $i
set i 'קּ'; set -gx i_mdi_grease_pencil $i
set i 'רּ'; set -gx i_mdi_human_female $i
set i 'שּ'; set -gx i_mdi_human_greeting $i
set i 'תּ'; set -gx i_mdi_human_handsdown $i
set i 'וֹ'; set -gx i_mdi_human_handsup $i
set i 'בֿ'; set -gx i_mdi_human_male $i
set i 'כֿ'; set -gx i_mdi_information_variant $i
set i 'פֿ'; set -gx i_mdi_lead_pencil $i
set i 'ﭏ'; set -gx i_mdi_map_marker_minus $i
set i 'ﭐ'; set -gx i_mdi_map_marker_plus $i
set i 'ﭑ'; set -gx i_mdi_marker $i
set i 'ﭒ'; set -gx i_mdi_message_plus $i
set i 'ﭓ'; set -gx i_mdi_microscope $i
set i 'ﭔ'; set -gx i_mdi_move_resize $i
set i 'ﭕ'; set -gx i_mdi_move_resize_variant $i
set i 'ﭖ'; set -gx i_mdi_paw_off $i
set i 'ﭗ'; set -gx i_mdi_phone_minus $i
set i 'ﭘ'; set -gx i_mdi_phone_plus $i
set i 'ﭙ'; set -gx i_mdi_pot $i
set i 'ﭚ'; set -gx i_mdi_pot_mix $i
set i 'ﭛ'; set -gx i_mdi_serial_port $i
set i 'ﭜ'; set -gx i_mdi_shape_circle_plus $i
set i 'ﭝ'; set -gx i_mdi_shape_polygon_plus $i
set i 'ﭞ'; set -gx i_mdi_shape_rectangle_plus $i
set i 'ﭟ'; set -gx i_mdi_shape_square_plus $i
set i 'ﭠ'; set -gx i_mdi_skip_next_circle $i
set i 'ﭡ'; set -gx i_mdi_skip_next_circle_outline $i
set i 'ﭢ'; set -gx i_mdi_skip_previous_circle $i
set i 'ﭣ'; set -gx i_mdi_skip_previous_circle_outline $i
set i 'ﭤ'; set -gx i_mdi_spray $i
set i 'ﭥ'; set -gx i_mdi_stop_circle $i
set i 'ﭦ'; set -gx i_mdi_stop_circle_outline $i
set i 'ﭧ'; set -gx i_mdi_test_tube $i
set i 'ﭨ'; set -gx i_mdi_text_shadow $i
set i 'ﭩ'; set -gx i_mdi_tune_vertical $i
set i 'ﭪ'; set -gx i_mdi_cart_off $i
set i 'ﭫ'; set -gx i_mdi_chart_gantt $i
set i 'ﭬ'; set -gx i_mdi_chart_scatterplot_hexbin $i
set i 'ﭭ'; set -gx i_mdi_chart_timeline $i
set i 'ﭮ'; set -gx i_mdi_discord $i
set i 'ﭯ'; set -gx i_mdi_file_restore $i
set i 'ﭰ'; set -gx i_mdi_language_c $i
set i 'ﭱ'; set -gx i_mdi_language_cpp $i
set i 'ﭲ'; set -gx i_mdi_xaml $i
set i 'ﭳ'; set -gx i_mdi_bandcamp $i
set i 'ﭴ'; set -gx i_mdi_credit_card_plus $i
set i 'ﭵ'; set -gx i_mdi_itunes $i
set i 'ﭶ'; set -gx i_mdi_bow_tie $i
set i 'ﭷ'; set -gx i_mdi_calendar_range $i
set i 'ﭸ'; set -gx i_mdi_currency_usd_off $i
set i 'ﭹ'; set -gx i_mdi_flash_red_eye $i
set i 'ﭺ'; set -gx i_mdi_oar $i
set i 'ﭻ'; set -gx i_mdi_piano $i
set i 'ﭼ'; set -gx i_mdi_weather_lightning_rainy $i
set i 'ﭽ'; set -gx i_mdi_weather_snowy_rainy $i
set i 'ﭾ'; set -gx i_mdi_yin_yang $i
set i 'ﭿ'; set -gx i_mdi_tower_beach $i
set i 'ﮀ'; set -gx i_mdi_tower_fire $i
set i 'ﮁ'; set -gx i_mdi_delete_circle $i
set i 'ﮂ'; set -gx i_mdi_dna $i
set i 'ﮃ'; set -gx i_mdi_hamburger $i
set i 'ﮄ'; set -gx i_mdi_gondola $i
set i 'ﮅ'; set -gx i_mdi_inbox $i
set i 'ﮆ'; set -gx i_mdi_reorder_horizontal $i
set i 'ﮇ'; set -gx i_mdi_reorder_vertical $i
set i 'ﮈ'; set -gx i_mdi_security_home $i
set i 'ﮉ'; set -gx i_mdi_tag_heart $i
set i 'ﮊ'; set -gx i_mdi_skull $i
set i 'ﮋ'; set -gx i_mdi_solid $i
set i 'ﮌ'; set -gx i_mdi_alarm_snooze $i
set i 'ﮍ'; set -gx i_mdi_baby_buggy $i
set i 'ﮎ'; set -gx i_mdi_beaker $i
set i 'ﮏ'; set -gx i_mdi_bomb $i
set i 'ﮐ'; set -gx i_mdi_calendar_question $i
set i 'ﮑ'; set -gx i_mdi_camera_burst $i
set i 'ﮒ'; set -gx i_mdi_code_tags_check $i
set i 'ﮓ'; set -gx i_mdi_coins $i
set i 'ﮔ'; set -gx i_mdi_crop_rotate $i
set i 'ﮕ'; set -gx i_mdi_developer_board $i
set i 'ﮖ'; set -gx i_mdi_do_not_disturb $i
set i 'ﮗ'; set -gx i_mdi_do_not_disturb_off $i
set i 'ﮘ'; set -gx i_mdi_douban $i
set i 'ﮙ'; set -gx i_mdi_emoticon_dead $i
set i 'ﮚ'; set -gx i_mdi_emoticon_excited $i
set i 'ﮛ'; set -gx i_mdi_folder_star $i
set i 'ﮜ'; set -gx i_mdi_format_color_text $i
set i 'ﮝ'; set -gx i_mdi_format_section $i
set i 'ﮞ'; set -gx i_mdi_gradient $i
set i 'ﮟ'; set -gx i_mdi_home_outline $i
set i 'ﮠ'; set -gx i_mdi_message_bulleted $i
set i 'ﮡ'; set -gx i_mdi_message_bulleted_off $i
set i 'ﮢ'; set -gx i_mdi_nuke $i
set i 'ﮣ'; set -gx i_mdi_power_plug $i
set i 'ﮤ'; set -gx i_mdi_power_plug_off $i
set i 'ﮥ'; set -gx i_mdi_publish $i
set i 'ﮦ'; set -gx i_mdi_restore $i
set i 'ﮧ'; set -gx i_mdi_robot $i
set i 'ﮨ'; set -gx i_mdi_format_rotate_90 $i
set i 'ﮩ'; set -gx i_mdi_scanner $i
set i 'ﮪ'; set -gx i_mdi_subway $i
set i 'ﮫ'; set -gx i_mdi_timer_sand_empty $i
set i 'ﮬ'; set -gx i_mdi_transit_transfer $i
set i 'ﮭ'; set -gx i_mdi_unity $i
set i 'ﮮ'; set -gx i_mdi_update $i
set i 'ﮯ'; set -gx i_mdi_watch_vibrate $i
set i 'ﮰ'; set -gx i_mdi_angular $i
set i 'ﮱ'; set -gx i_mdi_dolby $i
set i '﮲'; set -gx i_mdi_emby $i
set i '﮳'; set -gx i_mdi_lamp $i
set i '﮴'; set -gx i_mdi_menu_down_outline $i
set i '﮵'; set -gx i_mdi_menu_up_outline $i
set i '﮶'; set -gx i_mdi_note_multiple $i
set i '﮷'; set -gx i_mdi_note_multiple_outline $i
set i '﮸'; set -gx i_mdi_plex $i
set i '﮹'; set -gx i_mdi_plane_shield $i
set i '﮺'; set -gx i_mdi_account_edit $i
set i '﮻'; set -gx i_mdi_alert_decagram $i
set i '﮼'; set -gx i_mdi_all_inclusive $i
set i '﮽'; set -gx i_mdi_angularjs $i
set i '﮾'; set -gx i_mdi_arrow_down_box $i
set i '﮿'; set -gx i_mdi_arrow_left_box $i
set i '﯀'; set -gx i_mdi_arrow_right_box $i
set i '﯁'; set -gx i_mdi_arrow_up_box $i
set i '﯂'; set -gx i_mdi_asterisk $i
set i '﯃'; set -gx i_mdi_bomb_off $i
set i '﯄'; set -gx i_mdi_bootstrap $i
set i '﯅'; set -gx i_mdi_cards_variant $i
set i '﯆'; set -gx i_mdi_clipboard_flow $i
set i '﯇'; set -gx i_mdi_close_outline $i
set i '﯈'; set -gx i_mdi_coffee_outline $i
set i '﯉'; set -gx i_mdi_contacts $i
set i '﯊'; set -gx i_mdi_delete_empty $i
set i '﯋'; set -gx i_mdi_earth_box $i
set i '﯌'; set -gx i_mdi_earth_box_off $i
set i '﯍'; set -gx i_mdi_email_alert $i
set i '﯎'; set -gx i_mdi_eye_outline $i
set i '﯏'; set -gx i_mdi_eye_off_outline $i
set i '﯐'; set -gx i_mdi_fast_forward_outline $i
set i '﯑'; set -gx i_mdi_feather $i
set i '﯒'; set -gx i_mdi_find_replace $i
set i 'ﯓ'; set -gx i_mdi_flash_outline $i
set i 'ﯔ'; set -gx i_mdi_format_font $i
set i 'ﯕ'; set -gx i_mdi_format_page_break $i
set i 'ﯖ'; set -gx i_mdi_format_pilcrow $i
set i 'ﯗ'; set -gx i_mdi_garage $i
set i 'ﯘ'; set -gx i_mdi_garage_open $i
set i 'ﯙ'; set -gx i_mdi_github_face $i
set i 'ﯚ'; set -gx i_mdi_google_keep $i
set i 'ﯛ'; set -gx i_mdi_google_photos $i
set i 'ﯜ'; set -gx i_mdi_heart_half_full $i
set i 'ﯝ'; set -gx i_mdi_heart_half $i
set i 'ﯞ'; set -gx i_mdi_heart_half_outline $i
set i 'ﯟ'; set -gx i_mdi_hexagon_multiple $i
set i 'ﯠ'; set -gx i_mdi_hook $i
set i 'ﯡ'; set -gx i_mdi_hook_off $i
set i 'ﯢ'; set -gx i_mdi_infinity $i
set i 'ﯣ'; set -gx i_mdi_language_swift $i
set i 'ﯤ'; set -gx i_mdi_language_typescript $i
set i 'ﯥ'; set -gx i_mdi_laptop_off $i
set i 'ﯦ'; set -gx i_mdi_lightbulb_on $i
set i 'ﯧ'; set -gx i_mdi_lightbulb_on_outline $i
set i 'ﯨ'; set -gx i_mdi_lock_pattern $i
set i 'ﯩ'; set -gx i_mdi_loop $i
set i 'ﯪ'; set -gx i_mdi_magnify_minus_outline $i
set i 'ﯫ'; set -gx i_mdi_magnify_plus_outline $i
set i 'ﯬ'; set -gx i_mdi_mailbox $i
set i 'ﯭ'; set -gx i_mdi_medical_bag $i
set i 'ﯮ'; set -gx i_mdi_message_settings $i
set i 'ﯯ'; set -gx i_mdi_message_settings_variant $i
set i 'ﯰ'; set -gx i_mdi_minus_box_outline $i
set i 'ﯱ'; set -gx i_mdi_network $i
set i 'ﯲ'; set -gx i_mdi_download_network $i
set i 'ﯳ'; set -gx i_mdi_help_network $i
set i 'ﯴ'; set -gx i_mdi_upload_network $i
set i 'ﯵ'; set -gx i_mdi_npm $i
set i 'ﯶ'; set -gx i_mdi_nut $i
set i 'ﯷ'; set -gx i_mdi_octagram $i
set i 'ﯸ'; set -gx i_mdi_page_layout_body $i
set i 'ﯹ'; set -gx i_mdi_page_layout_footer $i
set i 'ﯺ'; set -gx i_mdi_page_layout_header $i
set i 'ﯻ'; set -gx i_mdi_page_layout_sidebar_left $i
set i 'ﯼ'; set -gx i_mdi_page_layout_sidebar_right $i
set i 'ﯽ'; set -gx i_mdi_pencil_circle $i
set i 'ﯾ'; set -gx i_mdi_pentagon $i
set i 'ﯿ'; set -gx i_mdi_pentagon_outline $i
set i 'ﰀ'; set -gx i_mdi_pillar $i
set i 'ﰁ'; set -gx i_mdi_pistol $i
set i 'ﰂ'; set -gx i_mdi_plus_box_outline $i
set i 'ﰃ'; set -gx i_mdi_plus_outline $i
set i 'ﰄ'; set -gx i_mdi_prescription $i
set i 'ﰅ'; set -gx i_mdi_printer_settings $i
set i 'ﰆ'; set -gx i_mdi_react $i
set i 'ﰇ'; set -gx i_mdi_restart $i
set i 'ﰈ'; set -gx i_mdi_rewind_outline $i
set i 'ﰉ'; set -gx i_mdi_rhombus $i
set i 'ﰊ'; set -gx i_mdi_rhombus_outline $i
set i 'ﰋ'; set -gx i_mdi_roomba $i
set i 'ﰌ'; set -gx i_mdi_run $i
set i 'ﰍ'; set -gx i_mdi_search_web $i
set i 'ﰎ'; set -gx i_mdi_shovel $i
set i 'ﰏ'; set -gx i_mdi_shovel_off $i
set i 'ﰐ'; set -gx i_mdi_signal_2g $i
set i 'ﰑ'; set -gx i_mdi_signal_3g $i
set i 'ﰒ'; set -gx i_mdi_signal_4g $i
set i 'ﰓ'; set -gx i_mdi_signal_hspa $i
set i 'ﰔ'; set -gx i_mdi_signal_hspa_plus $i
set i 'ﰕ'; set -gx i_mdi_snowflake $i
set i 'ﰖ'; set -gx i_mdi_source_commit $i
set i 'ﰗ'; set -gx i_mdi_source_commit_end $i
set i 'ﰘ'; set -gx i_mdi_source_commit_end_local $i
set i 'ﰙ'; set -gx i_mdi_source_commit_local $i
set i 'ﰚ'; set -gx i_mdi_source_commit_next_local $i
set i 'ﰛ'; set -gx i_mdi_source_commit_start $i
set i 'ﰜ'; set -gx i_mdi_source_commit_start_next_local $i
set i 'ﰝ'; set -gx i_mdi_speaker_wireless $i
set i 'ﰞ'; set -gx i_mdi_stadium $i
set i 'ﰟ'; set -gx i_mdi_svg $i
set i 'ﰠ'; set -gx i_mdi_tag_plus $i
set i 'ﰡ'; set -gx i_mdi_tag_remove $i
set i 'ﰢ'; set -gx i_mdi_ticket_percent $i
set i 'ﰣ'; set -gx i_mdi_tilde $i
set i 'ﰤ'; set -gx i_mdi_treasure_chest $i
set i 'ﰥ'; set -gx i_mdi_truck_trailer $i
set i 'ﰦ'; set -gx i_mdi_view_parallel $i
set i 'ﰧ'; set -gx i_mdi_view_sequential $i
set i 'ﰨ'; set -gx i_mdi_washing_machine $i
set i 'ﰩ'; set -gx i_mdi_webpack $i
set i 'ﰪ'; set -gx i_mdi_widgets $i
set i 'ﰫ'; set -gx i_mdi_wiiu $i
set i 'ﰬ'; set -gx i_mdi_arrow_down_bold $i
set i 'ﰭ'; set -gx i_mdi_arrow_down_bold_box $i
set i 'ﰮ'; set -gx i_mdi_arrow_down_bold_box_outline $i
set i 'ﰯ'; set -gx i_mdi_arrow_left_bold $i
set i 'ﰰ'; set -gx i_mdi_arrow_left_bold_box $i
set i 'ﰱ'; set -gx i_mdi_arrow_left_bold_box_outline $i
set i 'ﰲ'; set -gx i_mdi_arrow_right_bold $i
set i 'ﰳ'; set -gx i_mdi_arrow_right_bold_box $i
set i 'ﰴ'; set -gx i_mdi_arrow_right_bold_box_outline $i
set i 'ﰵ'; set -gx i_mdi_arrow_up_bold $i
set i 'ﰶ'; set -gx i_mdi_arrow_up_bold_box $i
set i 'ﰷ'; set -gx i_mdi_arrow_up_bold_box_outline $i
set i 'ﰸ'; set -gx i_mdi_cancel $i
set i 'ﰹ'; set -gx i_mdi_file_account $i
set i 'ﰺ'; set -gx i_mdi_gesture_double_tap $i
set i 'ﰻ'; set -gx i_mdi_gesture_swipe_down $i
set i 'ﰼ'; set -gx i_mdi_gesture_swipe_left $i
set i 'ﰽ'; set -gx i_mdi_gesture_swipe_right $i
set i 'ﰾ'; set -gx i_mdi_gesture_swipe_up $i
set i 'ﰿ'; set -gx i_mdi_gesture_tap $i
set i 'ﱀ'; set -gx i_mdi_gesture_two_double_tap $i
set i 'ﱁ'; set -gx i_mdi_gesture_two_tap $i
set i 'ﱂ'; set -gx i_mdi_humble_bundle $i
set i 'ﱃ'; set -gx i_mdi_kickstarter $i
set i 'ﱄ'; set -gx i_mdi_netflix $i
set i 'ﱅ'; set -gx i_mdi_onenote $i
set i 'ﱆ'; set -gx i_mdi_periscope $i
set i 'ﱇ'; set -gx i_mdi_uber $i
set i 'ﱈ'; set -gx i_mdi_vector_radius $i
set i 'ﱉ'; set -gx i_mdi_xbox_controller_battery_alert $i
set i 'ﱊ'; set -gx i_mdi_xbox_controller_battery_empty $i
set i 'ﱋ'; set -gx i_mdi_xbox_controller_battery_full $i
set i 'ﱌ'; set -gx i_mdi_xbox_controller_battery_low $i
set i 'ﱍ'; set -gx i_mdi_xbox_controller_battery_medium $i
set i 'ﱎ'; set -gx i_mdi_xbox_controller_battery_unknown $i
set i 'ﱏ'; set -gx i_mdi_clipboard_plus $i
set i 'ﱐ'; set -gx i_mdi_file_plus $i
set i 'ﱑ'; set -gx i_mdi_format_align_bottom $i
set i 'ﱒ'; set -gx i_mdi_format_align_middle $i
set i 'ﱓ'; set -gx i_mdi_format_align_top $i
set i 'ﱔ'; set -gx i_mdi_format_list_checks $i
set i 'ﱕ'; set -gx i_mdi_format_quote_open $i
set i 'ﱖ'; set -gx i_mdi_grid_large $i
set i 'ﱗ'; set -gx i_mdi_heart_off $i
set i 'ﱘ'; set -gx i_mdi_music $i
set i 'ﱙ'; set -gx i_mdi_music_off $i
set i 'ﱚ'; set -gx i_mdi_tab_plus $i
set i 'ﱛ'; set -gx i_mdi_volume_plus $i
set i 'ﱜ'; set -gx i_mdi_volume_minus $i
set i 'ﱝ'; set -gx i_mdi_volume_mute $i
set i 'ﱞ'; set -gx i_mdi_unfold_less_vertical $i
set i 'ﱟ'; set -gx i_mdi_unfold_more_vertical $i
set i 'ﱠ'; set -gx i_mdi_taco $i
set i 'ﱡ'; set -gx i_mdi_square_outline $i
set i 'ﱢ'; set -gx i_mdi_square $i
set i 'ﱣ'; set -gx i_mdi_circle $i
set i 'ﱤ'; set -gx i_mdi_circle_outline $i
set i 'ﱥ'; set -gx i_mdi_alert_octagram $i
set i 'ﱦ'; set -gx i_mdi_atom $i
set i 'ﱧ'; set -gx i_mdi_ceiling_light $i
set i 'ﱨ'; set -gx i_mdi_chart_bar_stacked $i
set i 'ﱩ'; set -gx i_mdi_chart_line_stacked $i
set i 'ﱪ'; set -gx i_mdi_decagram $i
set i 'ﱫ'; set -gx i_mdi_decagram_outline $i
set i 'ﱬ'; set -gx i_mdi_dice_multiple $i
set i 'ﱭ'; set -gx i_mdi_dice_d10 $i
set i 'ﱮ'; set -gx i_mdi_folder_open $i
set i 'ﱯ'; set -gx i_mdi_guitar_acoustic $i
set i 'ﱰ'; set -gx i_mdi_loading $i
set i 'ﱱ'; set -gx i_mdi_lock_reset $i
set i 'ﱲ'; set -gx i_mdi_ninja $i
set i 'ﱳ'; set -gx i_mdi_octagram_outline $i
set i 'ﱴ'; set -gx i_mdi_pencil_circle_outline $i
set i 'ﱵ'; set -gx i_mdi_selection_off $i
set i 'ﱶ'; set -gx i_mdi_set_all $i
set i 'ﱷ'; set -gx i_mdi_set_center $i
set i 'ﱸ'; set -gx i_mdi_set_center_right $i
set i 'ﱹ'; set -gx i_mdi_set_left $i
set i 'ﱺ'; set -gx i_mdi_set_left_center $i
set i 'ﱻ'; set -gx i_mdi_set_left_right $i
set i 'ﱼ'; set -gx i_mdi_set_none $i
set i 'ﱽ'; set -gx i_mdi_set_right $i
set i 'ﱾ'; set -gx i_mdi_shield_half_full $i
set i 'ﱿ'; set -gx i_mdi_sign_direction $i
set i 'ﲀ'; set -gx i_mdi_sign_text $i
set i 'ﲁ'; set -gx i_mdi_signal_off $i
set i 'ﲂ'; set -gx i_mdi_square_root $i
set i 'ﲃ'; set -gx i_mdi_sticker_emoji $i
set i 'ﲄ'; set -gx i_mdi_summit $i
set i 'ﲅ'; set -gx i_mdi_sword_cross $i
set i 'ﲆ'; set -gx i_mdi_truck_fast $i
set i 'ﲇ'; set -gx i_mdi_yammer $i
set i 'ﲈ'; set -gx i_mdi_cast_off $i
set i 'ﲉ'; set -gx i_mdi_help_box $i
set i 'ﲊ'; set -gx i_mdi_timer_sand_full $i
set i 'ﲋ'; set -gx i_mdi_waves $i
set i 'ﲌ'; set -gx i_mdi_alarm_bell $i
set i 'ﲍ'; set -gx i_mdi_alarm_light $i
set i 'ﲎ'; set -gx i_mdi_android_head $i
set i 'ﲏ'; set -gx i_mdi_approval $i
set i 'ﲐ'; set -gx i_mdi_arrow_collapse_down $i
set i 'ﲑ'; set -gx i_mdi_arrow_collapse_left $i
set i 'ﲒ'; set -gx i_mdi_arrow_collapse_right $i
set i 'ﲓ'; set -gx i_mdi_arrow_collapse_up $i
set i 'ﲔ'; set -gx i_mdi_arrow_expand_down $i
set i 'ﲕ'; set -gx i_mdi_arrow_expand_left $i
set i 'ﲖ'; set -gx i_mdi_arrow_expand_right $i
set i 'ﲗ'; set -gx i_mdi_arrow_expand_up $i
set i 'ﲘ'; set -gx i_mdi_book_secure $i
set i 'ﲙ'; set -gx i_mdi_book_unsecure $i
set i 'ﲚ'; set -gx i_mdi_bus_articulated_end $i
set i 'ﲛ'; set -gx i_mdi_bus_articulated_front $i
set i 'ﲜ'; set -gx i_mdi_bus_double_decker $i
set i 'ﲝ'; set -gx i_mdi_bus_school $i
set i 'ﲞ'; set -gx i_mdi_bus_side $i
set i 'ﲟ'; set -gx i_mdi_camera_gopro $i
set i 'ﲠ'; set -gx i_mdi_camera_metering_center $i
set i 'ﲡ'; set -gx i_mdi_camera_metering_matrix $i
set i 'ﲢ'; set -gx i_mdi_camera_metering_partial $i
set i 'ﲣ'; set -gx i_mdi_camera_metering_spot $i
set i 'ﲤ'; set -gx i_mdi_cannabis $i
set i 'ﲥ'; set -gx i_mdi_car_convertible $i
set i 'ﲦ'; set -gx i_mdi_car_estate $i
set i 'ﲧ'; set -gx i_mdi_car_hatchback $i
set i 'ﲨ'; set -gx i_mdi_car_pickup $i
set i 'ﲩ'; set -gx i_mdi_car_side $i
set i 'ﲪ'; set -gx i_mdi_car_sports $i
set i 'ﲫ'; set -gx i_mdi_caravan $i
set i 'ﲬ'; set -gx i_mdi_cctv $i
set i 'ﲭ'; set -gx i_mdi_chart_donut $i
set i 'ﲮ'; set -gx i_mdi_chart_donut_variant $i
set i 'ﲯ'; set -gx i_mdi_chart_line_variant $i
set i 'ﲰ'; set -gx i_mdi_chili_hot $i
set i 'ﲱ'; set -gx i_mdi_chili_medium $i
set i 'ﲲ'; set -gx i_mdi_chili_mild $i
set i 'ﲳ'; set -gx i_mdi_cloud_braces $i
set i 'ﲴ'; set -gx i_mdi_cloud_tags $i
set i 'ﲵ'; set -gx i_mdi_console_line $i
set i 'ﲶ'; set -gx i_mdi_corn $i
set i 'ﲷ'; set -gx i_mdi_currency_chf $i
set i 'ﲸ'; set -gx i_mdi_currency_cny $i
set i 'ﲹ'; set -gx i_mdi_currency_eth $i
set i 'ﲺ'; set -gx i_mdi_currency_jpy $i
set i 'ﲻ'; set -gx i_mdi_currency_krw $i
set i 'ﲼ'; set -gx i_mdi_currency_sign $i
set i 'ﲽ'; set -gx i_mdi_currency_twd $i
set i 'ﲾ'; set -gx i_mdi_desktop_classic $i
set i 'ﲿ'; set -gx i_mdi_dip_switch $i
set i 'ﳀ'; set -gx i_mdi_donkey $i
set i 'ﳁ'; set -gx i_mdi_dots_horizontal_circle $i
set i 'ﳂ'; set -gx i_mdi_dots_vertical_circle $i
set i 'ﳃ'; set -gx i_mdi_ear_hearing $i
set i 'ﳄ'; set -gx i_mdi_elephant $i
set i 'ﳅ'; set -gx i_mdi_eventbrite $i
set i 'ﳆ'; set -gx i_mdi_food_croissant $i
set i 'ﳇ'; set -gx i_mdi_forklift $i
set i 'ﳈ'; set -gx i_mdi_fuel $i
set i 'ﳉ'; set -gx i_mdi_gesture $i
set i 'ﳊ'; set -gx i_mdi_google_analytics $i
set i 'ﳋ'; set -gx i_mdi_google_assistant $i
set i 'ﳌ'; set -gx i_mdi_headphones_off $i
set i 'ﳍ'; set -gx i_mdi_high_definition $i
set i 'ﳎ'; set -gx i_mdi_home_assistant $i
set i 'ﳏ'; set -gx i_mdi_home_automation $i
set i 'ﳐ'; set -gx i_mdi_home_circle $i
set i 'ﳑ'; set -gx i_mdi_language_go $i
set i 'ﳒ'; set -gx i_mdi_language_r $i
set i 'ﳓ'; set -gx i_mdi_lava_lamp $i
set i 'ﳔ'; set -gx i_mdi_led_strip $i
set i 'ﳕ'; set -gx i_mdi_locker $i
set i 'ﳖ'; set -gx i_mdi_locker_multiple $i
set i 'ﳗ'; set -gx i_mdi_map_marker_outline $i
set i 'ﳘ'; set -gx i_mdi_metronome $i
set i 'ﳙ'; set -gx i_mdi_metronome_tick $i
set i 'ﳚ'; set -gx i_mdi_micro_sd $i
set i 'ﳛ'; set -gx i_mdi_mixer $i
set i 'ﳜ'; set -gx i_mdi_movie_roll $i
set i 'ﳝ'; set -gx i_mdi_mushroom $i
set i 'ﳞ'; set -gx i_mdi_mushroom_outline $i
set i 'ﳟ'; set -gx i_mdi_nintendo_switch $i
set i 'ﳠ'; set -gx i_mdi_null $i
set i 'ﳡ'; set -gx i_mdi_passport $i
set i 'ﳢ'; set -gx i_mdi_periodic_table_co2 $i
set i 'ﳣ'; set -gx i_mdi_pipe $i
set i 'ﳤ'; set -gx i_mdi_pipe_disconnected $i
set i 'ﳥ'; set -gx i_mdi_power_socket_eu $i
set i 'ﳦ'; set -gx i_mdi_power_socket_uk $i
set i 'ﳧ'; set -gx i_mdi_power_socket_us $i
set i 'ﳨ'; set -gx i_mdi_rice $i
set i 'ﳩ'; set -gx i_mdi_ring $i
set i 'ﳪ'; set -gx i_mdi_sass $i
set i 'ﳫ'; set -gx i_mdi_send_secure $i
set i 'ﳬ'; set -gx i_mdi_soy_sauce $i
set i 'ﳭ'; set -gx i_mdi_standard_definition $i
set i 'ﳮ'; set -gx i_mdi_surround_sound_2_0 $i
set i 'ﳯ'; set -gx i_mdi_surround_sound_3_1 $i
set i 'ﳰ'; set -gx i_mdi_surround_sound_5_1 $i
set i 'ﳱ'; set -gx i_mdi_surround_sound_7_1 $i
set i 'ﳲ'; set -gx i_mdi_television_classic $i
set i 'ﳳ'; set -gx i_mdi_textbox_password $i
set i 'ﳴ'; set -gx i_mdi_thought_bubble $i
set i 'ﳵ'; set -gx i_mdi_thought_bubble_outline $i
set i 'ﳶ'; set -gx i_mdi_trackpad $i
set i 'ﳷ'; set -gx i_mdi_ultra_high_definition $i
set i 'ﳸ'; set -gx i_mdi_van_passenger $i
set i 'ﳹ'; set -gx i_mdi_van_utility $i
set i 'ﳺ'; set -gx i_mdi_vanish $i
set i 'ﳻ'; set -gx i_mdi_video_3d $i
set i 'ﳼ'; set -gx i_mdi_wall $i
set i 'ﳽ'; set -gx i_mdi_xmpp $i
set i 'ﳾ'; set -gx i_mdi_account_multiple_plus_outline $i
set i 'ﳿ'; set -gx i_mdi_account_plus_outline $i
set i 'ﴀ'; set -gx i_mdi_allo $i
set i 'ﴁ'; set -gx i_mdi_artist $i
set i 'ﴂ'; set -gx i_mdi_atlassian $i
set i 'ﴃ'; set -gx i_mdi_azure $i
set i 'ﴄ'; set -gx i_mdi_basketball $i
set i 'ﴅ'; set -gx i_mdi_battery_charging_wireless $i
set i 'ﴆ'; set -gx i_mdi_battery_charging_wireless_10 $i
set i 'ﴇ'; set -gx i_mdi_battery_charging_wireless_20 $i
set i 'ﴈ'; set -gx i_mdi_battery_charging_wireless_30 $i
set i 'ﴉ'; set -gx i_mdi_battery_charging_wireless_40 $i
set i 'ﴊ'; set -gx i_mdi_battery_charging_wireless_50 $i
set i 'ﴋ'; set -gx i_mdi_battery_charging_wireless_60 $i
set i 'ﴌ'; set -gx i_mdi_battery_charging_wireless_70 $i
set i 'ﴍ'; set -gx i_mdi_battery_charging_wireless_80 $i
set i 'ﴎ'; set -gx i_mdi_battery_charging_wireless_90 $i
set i 'ﴏ'; set -gx i_mdi_battery_charging_wireless_alert $i
set i 'ﴐ'; set -gx i_mdi_battery_charging_wireless_outline $i
set i 'ﴑ'; set -gx i_mdi_bitcoin $i
set i 'ﴒ'; set -gx i_mdi_briefcase_outline $i
set i 'ﴓ'; set -gx i_mdi_cellphone_wireless $i
set i 'ﴔ'; set -gx i_mdi_clover $i
set i 'ﴕ'; set -gx i_mdi_comment_question $i
set i 'ﴖ'; set -gx i_mdi_content_save_outline $i
set i 'ﴗ'; set -gx i_mdi_delete_restore $i
set i 'ﴘ'; set -gx i_mdi_door $i
set i 'ﴙ'; set -gx i_mdi_door_closed $i
set i 'ﴚ'; set -gx i_mdi_door_open $i
set i 'ﴛ'; set -gx i_mdi_fan_off $i
set i 'ﴜ'; set -gx i_mdi_file_percent $i
set i 'ﴝ'; set -gx i_mdi_finance $i
set i 'ﴞ'; set -gx i_mdi_flash_circle $i
set i 'ﴟ'; set -gx i_mdi_floor_plan $i
set i 'ﴠ'; set -gx i_mdi_forum_outline $i
set i 'ﴡ'; set -gx i_mdi_golf $i
set i 'ﴢ'; set -gx i_mdi_google_home $i
set i 'ﴣ'; set -gx i_mdi_guy_fawkes_mask $i
set i 'ﴤ'; set -gx i_mdi_home_account $i
set i 'ﴥ'; set -gx i_mdi_home_heart $i
set i 'ﴦ'; set -gx i_mdi_hot_tub $i
set i 'ﴧ'; set -gx i_mdi_hulu $i
set i 'ﴨ'; set -gx i_mdi_ice_cream $i
set i 'ﴩ'; set -gx i_mdi_image_off $i
set i 'ﴪ'; set -gx i_mdi_karate $i
set i 'ﴫ'; set -gx i_mdi_ladybug $i
set i 'ﴬ'; set -gx i_mdi_notebook $i
set i 'ﴭ'; set -gx i_mdi_phone_return $i
set i 'ﴮ'; set -gx i_mdi_poker_chip $i
set i 'ﴯ'; set -gx i_mdi_shape $i
set i 'ﴰ'; set -gx i_mdi_shape_outline $i
set i 'ﴱ'; set -gx i_mdi_ship_wheel $i
set i 'ﴲ'; set -gx i_mdi_soccer_field $i
set i 'ﴳ'; set -gx i_mdi_table_column $i
set i 'ﴴ'; set -gx i_mdi_table_of_contents $i
set i 'ﴵ'; set -gx i_mdi_table_row $i
set i 'ﴶ'; set -gx i_mdi_table_settings $i
set i 'ﴷ'; set -gx i_mdi_television_box $i
set i 'ﴸ'; set -gx i_mdi_television_classic_off $i
set i 'ﴹ'; set -gx i_mdi_television_off $i
set i 'ﴺ'; set -gx i_mdi_towing $i
set i 'ﴻ'; set -gx i_mdi_upload_multiple $i
set i 'ﴼ'; set -gx i_mdi_video_4k_box $i
set i 'ﴽ'; set -gx i_mdi_video_input_antenna $i
set i '﴾'; set -gx i_mdi_video_input_component $i
set i '﴿'; set -gx i_mdi_video_input_hdmi $i
set i '﵀'; set -gx i_mdi_video_input_svideo $i
set i '﵁'; set -gx i_mdi_view_dashboard_variant $i
set i '﵂'; set -gx i_mdi_vuejs $i
set i '﵃'; set -gx i_mdi_xamarin $i
set i '﵄'; set -gx i_mdi_xamarin_outline $i
set i '﵅'; set -gx i_mdi_youtube_creator_studio $i
set i '﵆'; set -gx i_mdi_youtube_gaming $i
