# Octicons (172 icons)
# Codepoints: 2665, 26A1, Nerd Fonts moved F000-F105 with holes → F400-F4A8, F27C → F67C
set i '♥'; set -gx i_oct_heart $i
set i '⚡'; set -gx i_oct_zap $i
set i ''; set -gx i_oct_light_bulb $i
set i ''; set -gx i_oct_repo $i
set i ''; set -gx i_oct_repo_forked $i
set i ''; set -gx i_oct_repo_push $i
set i ''; set -gx i_oct_repo_pull $i
set i ''; set -gx i_oct_book $i
set i ''; set -gx i_oct_octoface $i
set i ''; set -gx i_oct_git_pull_request $i
set i ''; set -gx i_oct_mark_github $i
set i ''; set -gx i_oct_cloud_download $i
set i ''; set -gx i_oct_cloud_upload $i
set i ''; set -gx i_oct_keyboard $i
set i ''; set -gx i_oct_gist $i
set i ''; set -gx i_oct_file_code $i
set i ''; set -gx i_oct_file_text $i
set i ''; set -gx i_oct_file_media $i
set i ''; set -gx i_oct_file_zip $i
set i ''; set -gx i_oct_file_pdf $i
set i ''; set -gx i_oct_tag $i
set i ''; set -gx i_oct_file_directory $i
set i ''; set -gx i_oct_file_submodule $i
set i ''; set -gx i_oct_person $i
set i ''; set -gx i_oct_jersey $i
set i ''; set -gx i_oct_git_commit $i
set i ''; set -gx i_oct_git_branch $i
set i ''; set -gx i_oct_git_merge $i
set i ''; set -gx i_oct_mirror $i
set i ''; set -gx i_oct_issue_opened $i
set i ''; set -gx i_oct_issue_reopened $i
set i ''; set -gx i_oct_issue_closed $i
set i ''; set -gx i_oct_star $i
set i ''; set -gx i_oct_comment $i
set i ''; set -gx i_oct_question $i
set i ''; set -gx i_oct_alert $i
set i ''; set -gx i_oct_search $i
set i ''; set -gx i_oct_gear $i
set i ''; set -gx i_oct_radio_tower $i
set i ''; set -gx i_oct_tools $i
set i ''; set -gx i_oct_sign_out $i
set i ''; set -gx i_oct_rocket $i
set i ''; set -gx i_oct_rss $i
set i ''; set -gx i_oct_clippy $i
set i ''; set -gx i_oct_sign_in $i
set i ''; set -gx i_oct_organization $i
set i ''; set -gx i_oct_device_mobile $i
set i ''; set -gx i_oct_unfold $i
set i ''; set -gx i_oct_check $i
set i ''; set -gx i_oct_mail $i
set i ''; set -gx i_oct_mail_read $i
set i ''; set -gx i_oct_arrow_up $i
set i ''; set -gx i_oct_arrow_right $i
set i ''; set -gx i_oct_arrow_down $i
set i ''; set -gx i_oct_arrow_left $i
set i ''; set -gx i_oct_pin $i
set i ''; set -gx i_oct_gift $i
set i ''; set -gx i_oct_graph $i
set i ''; set -gx i_oct_triangle_left $i
set i ''; set -gx i_oct_credit_card $i
set i ''; set -gx i_oct_clock $i
set i ''; set -gx i_oct_ruby $i
set i ''; set -gx i_oct_broadcast $i
set i ''; set -gx i_oct_key $i
set i ''; set -gx i_oct_repo_force_push $i
set i ''; set -gx i_oct_repo_clone $i
set i ''; set -gx i_oct_diff $i
set i ''; set -gx i_oct_eye $i
set i ''; set -gx i_oct_comment_discussion $i
set i ''; set -gx i_oct_mail_reply $i
set i ''; set -gx i_oct_primitive_dot $i
set i ''; set -gx i_oct_primitive_square $i
set i ''; set -gx i_oct_device_camera $i
set i ''; set -gx i_oct_device_camera_video $i
set i ''; set -gx i_oct_pencil $i
set i ''; set -gx i_oct_info $i
set i ''; set -gx i_oct_triangle_right $i
set i ''; set -gx i_oct_triangle_down $i
set i ''; set -gx i_oct_link $i
set i ''; set -gx i_oct_plus $i
set i ''; set -gx i_oct_three_bars $i
set i ''; set -gx i_oct_code $i
set i ''; set -gx i_oct_location $i
set i ''; set -gx i_oct_list_unordered $i
set i ''; set -gx i_oct_list_ordered $i
set i ''; set -gx i_oct_quote $i
set i ''; set -gx i_oct_versions $i
set i ''; set -gx i_oct_calendar $i
set i ''; set -gx i_oct_lock $i
set i ''; set -gx i_oct_diff_added $i
set i ''; set -gx i_oct_diff_removed $i
set i ''; set -gx i_oct_diff_modified $i
set i ''; set -gx i_oct_diff_renamed $i
set i ''; set -gx i_oct_horizontal_rule $i
set i ''; set -gx i_oct_arrow_small_right $i
set i ''; set -gx i_oct_milestone $i
set i ''; set -gx i_oct_checklist $i
set i ''; set -gx i_oct_megaphone $i
set i ''; set -gx i_oct_chevron_right $i
set i ''; set -gx i_oct_bookmark $i
set i ''; set -gx i_oct_settings $i
set i ''; set -gx i_oct_dashboard $i
set i ''; set -gx i_oct_history $i
set i ''; set -gx i_oct_link_external $i
set i ''; set -gx i_oct_mute $i
set i ''; set -gx i_oct_x $i
set i ''; set -gx i_oct_circle_slash $i
set i ''; set -gx i_oct_pulse $i
set i ''; set -gx i_oct_sync $i
set i ''; set -gx i_oct_telescope $i
set i ''; set -gx i_oct_gist_secret $i
set i ''; set -gx i_oct_home $i
set i ''; set -gx i_oct_stop $i
set i ''; set -gx i_oct_bug $i
set i ''; set -gx i_oct_logo_github $i
set i ''; set -gx i_oct_file_binary $i
set i ''; set -gx i_oct_database $i
set i ''; set -gx i_oct_server $i
set i ''; set -gx i_oct_diff_ignored $i
set i ''; set -gx i_oct_ellipsis $i
set i ''; set -gx i_oct_no_newline $i
set i ''; set -gx i_oct_hubot $i
set i ''; set -gx i_oct_arrow_small_up $i
set i ''; set -gx i_oct_arrow_small_down $i
set i ''; set -gx i_oct_arrow_small_left $i
set i ''; set -gx i_oct_chevron_up $i
set i ''; set -gx i_oct_chevron_down $i
set i ''; set -gx i_oct_chevron_left $i
set i ''; set -gx i_oct_triangle_up $i
set i ''; set -gx i_oct_git_compare $i
set i ''; set -gx i_oct_logo_gist $i
set i ''; set -gx i_oct_file_symlink_file $i
set i ''; set -gx i_oct_file_symlink_directory $i
set i ''; set -gx i_oct_squirrel $i
set i ''; set -gx i_oct_globe $i
set i ''; set -gx i_oct_unmute $i
set i ''; set -gx i_oct_mention $i
set i ''; set -gx i_oct_package $i
set i ''; set -gx i_oct_browser $i
set i ''; set -gx i_oct_terminal $i
set i ''; set -gx i_oct_markdown $i
set i ''; set -gx i_oct_dash $i
set i ''; set -gx i_oct_fold $i
set i ''; set -gx i_oct_inbox $i
set i ''; set -gx i_oct_trashcan $i
set i ''; set -gx i_oct_paintcan $i
set i ''; set -gx i_oct_flame $i
set i ''; set -gx i_oct_briefcase $i
set i ''; set -gx i_oct_plug $i
set i ''; set -gx i_oct_circuit_board $i
set i ''; set -gx i_oct_mortar_board $i
set i ''; set -gx i_oct_law $i
set i ''; set -gx i_oct_thumbsup $i
set i ''; set -gx i_oct_thumbsdown $i
set i ''; set -gx i_oct_desktop_download $i
set i ''; set -gx i_oct_beaker $i
set i ''; set -gx i_oct_bell $i
set i ''; set -gx i_oct_watch $i
set i ''; set -gx i_oct_shield $i
set i ''; set -gx i_oct_bold $i
set i ''; set -gx i_oct_text_size $i
set i ''; set -gx i_oct_italic $i
set i ''; set -gx i_oct_tasklist $i
set i ''; set -gx i_oct_verified $i
set i ''; set -gx i_oct_smiley $i
set i ''; set -gx i_oct_unverified $i
set i ''; set -gx i_oct_ellipses $i
set i ''; set -gx i_oct_file $i
set i ''; set -gx i_oct_grabber $i
set i ''; set -gx i_oct_plus_small $i
set i ''; set -gx i_oct_reply $i
set i ''; set -gx i_oct_device_desktop $i

