# Weather Icons (228 icons)
# Codepoints: F000, F0EB, Nerd Fonts moved E300-E3EB
# Nerd Fonts Version: 2.0.0
# Script Version 1.0.2
set i ''; set -gx i_weather_day_cloudy_gusts $i
set i ''; set -gx i_weather_day_cloudy_windy $i
set i ''; set -gx i_weather_day_cloudy $i
set i ''; set -gx i_weather_day_fog $i
set i ''; set -gx i_weather_day_hail $i
set i ''; set -gx i_weather_day_lightning $i
set i ''; set -gx i_weather_day_rain_mix $i
set i ''; set -gx i_weather_day_rain_wind $i
set i ''; set -gx i_weather_day_rain $i
set i ''; set -gx i_weather_day_showers $i
set i ''; set -gx i_weather_day_snow $i
set i ''; set -gx i_weather_day_sprinkle $i
set i ''; set -gx i_weather_day_sunny_overcast $i
set i ''; set -gx i_weather_day_sunny $i
set i ''; set -gx i_weather_day_storm_showers $i
set i ''; set -gx i_weather_day_thunderstorm $i
set i ''; set -gx i_weather_cloudy_gusts $i
set i ''; set -gx i_weather_cloudy_windy $i
set i ''; set -gx i_weather_cloudy $i
set i ''; set -gx i_weather_fog $i
set i ''; set -gx i_weather_hail $i
set i ''; set -gx i_weather_lightning $i
set i ''; set -gx i_weather_rain_mix $i
set i ''; set -gx i_weather_rain_wind $i
set i ''; set -gx i_weather_rain $i
set i ''; set -gx i_weather_showers $i
set i ''; set -gx i_weather_snow $i
set i ''; set -gx i_weather_sprinkle $i
set i ''; set -gx i_weather_storm_showers $i
set i ''; set -gx i_weather_thunderstorm $i
set i ''; set -gx i_weather_windy $i
set i ''; set -gx i_weather_night_alt_cloudy_gusts $i
set i ''; set -gx i_weather_night_alt_cloudy_windy $i
set i ''; set -gx i_weather_night_alt_hail $i
set i ''; set -gx i_weather_night_alt_lightning $i
set i ''; set -gx i_weather_night_alt_rain_mix $i
set i ''; set -gx i_weather_night_alt_rain_wind $i
set i ''; set -gx i_weather_night_alt_rain $i
set i ''; set -gx i_weather_night_alt_rain_mix $i
set i ''; set -gx i_weather_night_alt_snow $i
set i ''; set -gx i_weather_night_alt_sprinkle $i
set i ''; set -gx i_weather_night_alt_storm_showers $i
set i ''; set -gx i_weather_night_alt_thunderstorm $i
set i ''; set -gx i_weather_night_clear $i
set i ''; set -gx i_weather_night_cloudy_gusts $i
set i ''; set -gx i_weather_night_cloudy_windy $i
set i ''; set -gx i_weather_night_cloudy $i
set i ''; set -gx i_weather_night_hail $i
set i ''; set -gx i_weather_night_lightning $i
set i ''; set -gx i_weather_night_rain_mix $i
set i ''; set -gx i_weather_night_rain_wind $i
set i ''; set -gx i_weather_night_rain $i
set i ''; set -gx i_weather_night_showers $i
set i ''; set -gx i_weather_night_snow $i
set i ''; set -gx i_weather_night_sprinkle $i
set i ''; set -gx i_weather_night_storm_showers $i
set i ''; set -gx i_weather_night_thunderstorm $i
set i ''; set -gx i_weather_celsius $i
set i ''; set -gx i_weather_cloud_down $i
set i ''; set -gx i_weather_cloud_refresh $i
set i ''; set -gx i_weather_cloud_up $i
set i ''; set -gx i_weather_cloud $i
set i ''; set -gx i_weather_degrees $i
set i ''; set -gx i_weather_direction_down_left $i
set i ''; set -gx i_weather_direction_down $i
set i ''; set -gx i_weather_fahrenheit $i
set i ''; set -gx i_weather_horizon_alt $i
set i ''; set -gx i_weather_horizon $i
set i ''; set -gx i_weather_direction_left $i
set i ''; set -gx i_weather_aliens $i
set i ''; set -gx i_weather_night_fog $i
set i ''; set -gx i_weather_refresh_alt $i
set i ''; set -gx i_weather_refresh $i
set i ''; set -gx i_weather_direction_right $i
set i ''; set -gx i_weather_raindrops $i
set i ''; set -gx i_weather_strong_wind $i
set i ''; set -gx i_weather_sunrise $i
set i ''; set -gx i_weather_sunset $i
set i ''; set -gx i_weather_thermometer_exterior $i
set i ''; set -gx i_weather_thermometer_internal $i
set i ''; set -gx i_weather_thermometer $i
set i ''; set -gx i_weather_tornado $i
set i ''; set -gx i_weather_direction_up_right $i
set i ''; set -gx i_weather_direction_up $i
set i ''; set -gx i_weather_wind_west $i
set i ''; set -gx i_weather_wind_south_west $i
set i ''; set -gx i_weather_wind_south_east $i
set i ''; set -gx i_weather_wind_south $i
set i ''; set -gx i_weather_wind_north_west $i
set i ''; set -gx i_weather_wind_north_east $i
set i ''; set -gx i_weather_wind_north $i
set i ''; set -gx i_weather_wind_east $i
set i ''; set -gx i_weather_smoke $i
set i ''; set -gx i_weather_dust $i
set i ''; set -gx i_weather_snow_wind $i
set i ''; set -gx i_weather_day_snow_wind $i
set i ''; set -gx i_weather_night_snow_wind $i
set i ''; set -gx i_weather_night_alt_snow_wind $i
set i ''; set -gx i_weather_day_sleet_storm $i
set i ''; set -gx i_weather_night_sleet_storm $i
set i ''; set -gx i_weather_night_alt_sleet_storm $i
set i ''; set -gx i_weather_day_snow_thunderstorm $i
set i ''; set -gx i_weather_night_snow_thunderstorm $i
set i ''; set -gx i_weather_night_alt_snow_thunderstorm $i
set i ''; set -gx i_weather_solar_eclipse $i
set i ''; set -gx i_weather_lunar_eclipse $i
set i ''; set -gx i_weather_meteor $i
set i ''; set -gx i_weather_hot $i
set i ''; set -gx i_weather_hurricane $i
set i ''; set -gx i_weather_smog $i
set i ''; set -gx i_weather_alien $i
set i ''; set -gx i_weather_snowflake_cold $i
set i ''; set -gx i_weather_stars $i
set i ''; set -gx i_weather_raindrop $i
set i ''; set -gx i_weather_barometer $i
set i ''; set -gx i_weather_humidity $i
set i ''; set -gx i_weather_na $i
set i ''; set -gx i_weather_flood $i
set i ''; set -gx i_weather_day_cloudy_high $i
set i ''; set -gx i_weather_night_alt_cloudy_high $i
set i ''; set -gx i_weather_night_cloudy_high $i
set i ''; set -gx i_weather_night_alt_partly_cloudy $i
set i ''; set -gx i_weather_sandstorm $i
set i ''; set -gx i_weather_night_partly_cloudy $i
set i ''; set -gx i_weather_umbrella $i
set i ''; set -gx i_weather_day_windy $i
set i ''; set -gx i_weather_night_alt_cloudy $i
set i ''; set -gx i_weather_direction_up_left $i
set i ''; set -gx i_weather_direction_down_right $i
set i ''; set -gx i_weather_time_12 $i
set i ''; set -gx i_weather_time_1 $i
set i ''; set -gx i_weather_time_2 $i
set i ''; set -gx i_weather_time_3 $i
set i ''; set -gx i_weather_time_4 $i
set i ''; set -gx i_weather_time_5 $i
set i ''; set -gx i_weather_time_6 $i
set i ''; set -gx i_weather_time_7 $i
set i ''; set -gx i_weather_time_8 $i
set i ''; set -gx i_weather_time_9 $i
set i ''; set -gx i_weather_time_10 $i
set i ''; set -gx i_weather_time_11 $i
set i ''; set -gx i_weather_moon_new $i
set i ''; set -gx i_weather_moon_waxing_crescent_1 $i
set i ''; set -gx i_weather_moon_waxing_crescent_2 $i
set i ''; set -gx i_weather_moon_waxing_crescent_3 $i
set i ''; set -gx i_weather_moon_waxing_crescent_4 $i
set i ''; set -gx i_weather_moon_waxing_crescent_5 $i
set i ''; set -gx i_weather_moon_waxing_crescent_6 $i
set i ''; set -gx i_weather_moon_first_quarter $i
set i ''; set -gx i_weather_moon_waxing_gibbous_1 $i
set i ''; set -gx i_weather_moon_waxing_gibbous_2 $i
set i ''; set -gx i_weather_moon_waxing_gibbous_3 $i
set i ''; set -gx i_weather_moon_waxing_gibbous_4 $i
set i ''; set -gx i_weather_moon_waxing_gibbous_5 $i
set i ''; set -gx i_weather_moon_waxing_gibbous_6 $i
set i ''; set -gx i_weather_moon_full $i
set i ''; set -gx i_weather_moon_waning_gibbous_1 $i
set i ''; set -gx i_weather_moon_waning_gibbous_2 $i
set i ''; set -gx i_weather_moon_waning_gibbous_3 $i
set i ''; set -gx i_weather_moon_waning_gibbous_4 $i
set i ''; set -gx i_weather_moon_waning_gibbous_5 $i
set i ''; set -gx i_weather_moon_waning_gibbous_6 $i
set i ''; set -gx i_weather_moon_third_quarter $i
set i ''; set -gx i_weather_moon_waning_crescent_1 $i
set i ''; set -gx i_weather_moon_waning_crescent_2 $i
set i ''; set -gx i_weather_moon_waning_crescent_3 $i
set i ''; set -gx i_weather_moon_waning_crescent_4 $i
set i ''; set -gx i_weather_moon_waning_crescent_5 $i
set i ''; set -gx i_weather_moon_waning_crescent_6 $i
set i ''; set -gx i_weather_wind_direction $i
set i ''; set -gx i_weather_day_sleet $i
set i ''; set -gx i_weather_night_sleet $i
set i ''; set -gx i_weather_night_alt_sleet $i
set i ''; set -gx i_weather_sleet $i
set i ''; set -gx i_weather_day_haze $i
set i ''; set -gx i_weather_wind_beaufort_0 $i
set i ''; set -gx i_weather_wind_beaufort_1 $i
set i ''; set -gx i_weather_wind_beaufort_2 $i
set i ''; set -gx i_weather_wind_beaufort_3 $i
set i ''; set -gx i_weather_wind_beaufort_4 $i
set i ''; set -gx i_weather_wind_beaufort_5 $i
set i ''; set -gx i_weather_wind_beaufort_6 $i
set i ''; set -gx i_weather_wind_beaufort_7 $i
set i ''; set -gx i_weather_wind_beaufort_8 $i
set i ''; set -gx i_weather_wind_beaufort_9 $i
set i ''; set -gx i_weather_wind_beaufort_10 $i
set i ''; set -gx i_weather_wind_beaufort_11 $i
set i ''; set -gx i_weather_wind_beaufort_12 $i
set i ''; set -gx i_weather_day_light_wind $i
set i ''; set -gx i_weather_tsunami $i
set i ''; set -gx i_weather_earthquake $i
set i ''; set -gx i_weather_fire $i
set i ''; set -gx i_weather_volcano $i
set i ''; set -gx i_weather_moonrise $i
set i ''; set -gx i_weather_moonset $i
set i ''; set -gx i_weather_train $i
set i ''; set -gx i_weather_small_craft_advisory $i
set i ''; set -gx i_weather_gale_warning $i
set i ''; set -gx i_weather_storm_warning $i
set i ''; set -gx i_weather_hurricane_warning $i
set i ''; set -gx i_weather_moon_alt_waxing_crescent_1 $i
set i ''; set -gx i_weather_moon_alt_waxing_crescent_2 $i
set i ''; set -gx i_weather_moon_alt_waxing_crescent_3 $i
set i ''; set -gx i_weather_moon_alt_waxing_crescent_4 $i
set i ''; set -gx i_weather_moon_alt_waxing_crescent_5 $i
set i ''; set -gx i_weather_moon_alt_waxing_crescent_6 $i
set i ''; set -gx i_weather_moon_alt_first_quarter $i
set i ''; set -gx i_weather_moon_alt_waxing_gibbous_1 $i
set i ''; set -gx i_weather_moon_alt_waxing_gibbous_2 $i
set i ''; set -gx i_weather_moon_alt_waxing_gibbous_3 $i
set i ''; set -gx i_weather_moon_alt_waxing_gibbous_4 $i
set i ''; set -gx i_weather_moon_alt_waxing_gibbous_5 $i
set i ''; set -gx i_weather_moon_alt_waxing_gibbous_6 $i
set i ''; set -gx i_weather_moon_alt_full $i
set i ''; set -gx i_weather_moon_alt_waning_gibbous_1 $i
set i ''; set -gx i_weather_moon_alt_waning_gibbous_2 $i
set i ''; set -gx i_weather_moon_alt_waning_gibbous_3 $i
set i ''; set -gx i_weather_moon_alt_waning_gibbous_4 $i
set i ''; set -gx i_weather_moon_alt_waning_gibbous_5 $i
set i ''; set -gx i_weather_moon_alt_waning_gibbous_6 $i
set i ''; set -gx i_weather_moon_alt_third_quarter $i
set i ''; set -gx i_weather_moon_alt_waning_crescent_1 $i
set i ''; set -gx i_weather_moon_alt_waning_crescent_2 $i
set i ''; set -gx i_weather_moon_alt_waning_crescent_3 $i
set i ''; set -gx i_weather_moon_alt_waning_crescent_4 $i
set i ''; set -gx i_weather_moon_alt_waning_crescent_5 $i
set i ''; set -gx i_weather_moon_alt_waning_crescent_6 $i
set i ''; set -gx i_weather_moon_alt_new $i

