#!/usr/bin/env bash

set -e

mkdir -p ~/google/personal/
mount | grep "${HOME}/google/personal" >/dev/null || google-drive-ocamlfuse ~/google/personal/

mkdir -p ~/google/exira/
mount | grep "${HOME}/google/exira" >/dev/null || google-drive-ocamlfuse -label exira ~/google/exira/
